// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "softmax_latency_ap_fixed_ap_fixed_softmax_config10_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_boolean_1 = true;
const bool softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_boolean_0 = false;
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv32_6 = "110";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv32_F = "1111";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv32_11 = "10001";
const sc_lv<17> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv17_1FFFF = "11111111111111111";
const sc_lv<18> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv18_1FFFF = "11111111111111111";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv32_12 = "10010";
const sc_lv<1> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv1_1 = "1";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv32_8 = "1000";
const sc_lv<10> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv10_1FF = "111111111";
const sc_lv<10> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv10_200 = "1000000000";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv32_A = "1010";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::ap_const_lv32_19 = "11001";

softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::softmax_latency_ap_fixed_ap_fixed_softmax_config10_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    exp_table1_U = new softmax_latency_ap_fixed_ap_fixed_softmax_config10_s_exp_dEe("exp_table1_U");
    exp_table1_U->clk(ap_clk);
    exp_table1_U->reset(ap_rst);
    exp_table1_U->address0(exp_table1_address0);
    exp_table1_U->ce0(exp_table1_ce0);
    exp_table1_U->q0(exp_table1_q0);
    exp_table1_U->address1(exp_table1_address1);
    exp_table1_U->ce1(exp_table1_ce1);
    exp_table1_U->q1(exp_table1_q1);
    exp_table1_U->address2(exp_table1_address2);
    exp_table1_U->ce2(exp_table1_ce2);
    exp_table1_U->q2(exp_table1_q2);
    exp_table1_U->address3(exp_table1_address3);
    exp_table1_U->ce3(exp_table1_ce3);
    exp_table1_U->q3(exp_table1_q3);
    exp_table1_U->address4(exp_table1_address4);
    exp_table1_U->ce4(exp_table1_ce4);
    exp_table1_U->q4(exp_table1_q4);
    exp_table1_U->address5(exp_table1_address5);
    exp_table1_U->ce5(exp_table1_ce5);
    exp_table1_U->q5(exp_table1_q5);
    exp_table1_U->address6(exp_table1_address6);
    exp_table1_U->ce6(exp_table1_ce6);
    exp_table1_U->q6(exp_table1_q6);
    exp_table1_U->address7(exp_table1_address7);
    exp_table1_U->ce7(exp_table1_ce7);
    exp_table1_U->q7(exp_table1_q7);
    exp_table1_U->address8(exp_table1_address8);
    exp_table1_U->ce8(exp_table1_ce8);
    exp_table1_U->q8(exp_table1_q8);
    exp_table1_U->address9(exp_table1_address9);
    exp_table1_U->ce9(exp_table1_ce9);
    exp_table1_U->q9(exp_table1_q9);
    invert_table2_U = new softmax_latency_ap_fixed_ap_fixed_softmax_config10_s_inveeOg("invert_table2_U");
    invert_table2_U->clk(ap_clk);
    invert_table2_U->reset(ap_rst);
    invert_table2_U->address0(invert_table2_address0);
    invert_table2_U->ce0(invert_table2_ce0);
    invert_table2_U->q0(invert_table2_q0);
    myproject_mul_mul_17ns_18s_26_1_1_U861 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U861");
    myproject_mul_mul_17ns_18s_26_1_1_U861->din0(mul_ln1118_fu_985_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U861->din1(mul_ln1118_fu_985_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U861->dout(mul_ln1118_fu_985_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U862 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U862");
    myproject_mul_mul_17ns_18s_26_1_1_U862->din0(mul_ln1118_1_fu_992_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U862->din1(mul_ln1118_1_fu_992_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U862->dout(mul_ln1118_1_fu_992_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U863 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U863");
    myproject_mul_mul_17ns_18s_26_1_1_U863->din0(mul_ln1118_2_fu_999_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U863->din1(mul_ln1118_2_fu_999_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U863->dout(mul_ln1118_2_fu_999_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U864 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U864");
    myproject_mul_mul_17ns_18s_26_1_1_U864->din0(mul_ln1118_3_fu_1006_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U864->din1(mul_ln1118_3_fu_1006_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U864->dout(mul_ln1118_3_fu_1006_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U865 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U865");
    myproject_mul_mul_17ns_18s_26_1_1_U865->din0(mul_ln1118_4_fu_1013_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U865->din1(mul_ln1118_4_fu_1013_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U865->dout(mul_ln1118_4_fu_1013_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U866 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U866");
    myproject_mul_mul_17ns_18s_26_1_1_U866->din0(mul_ln1118_5_fu_1020_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U866->din1(mul_ln1118_5_fu_1020_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U866->dout(mul_ln1118_5_fu_1020_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U867 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U867");
    myproject_mul_mul_17ns_18s_26_1_1_U867->din0(mul_ln1118_6_fu_1027_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U867->din1(mul_ln1118_6_fu_1027_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U867->dout(mul_ln1118_6_fu_1027_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U868 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U868");
    myproject_mul_mul_17ns_18s_26_1_1_U868->din0(mul_ln1118_7_fu_1034_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U868->din1(mul_ln1118_7_fu_1034_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U868->dout(mul_ln1118_7_fu_1034_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U869 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U869");
    myproject_mul_mul_17ns_18s_26_1_1_U869->din0(mul_ln1118_8_fu_1041_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U869->din1(mul_ln1118_8_fu_1041_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U869->dout(mul_ln1118_8_fu_1041_p2);
    myproject_mul_mul_17ns_18s_26_1_1_U870 = new myproject_mul_mul_17ns_18s_26_1_1<1,1,17,18,26>("myproject_mul_mul_17ns_18s_26_1_1_U870");
    myproject_mul_mul_17ns_18s_26_1_1_U870->din0(mul_ln1118_9_fu_1048_p0);
    myproject_mul_mul_17ns_18s_26_1_1_U870->din1(mul_ln1118_9_fu_1048_p1);
    myproject_mul_mul_17ns_18s_26_1_1_U870->dout(mul_ln1118_9_fu_1048_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln746_1_fu_564_p2);
    sensitive << ( exp_table1_q2 );
    sensitive << ( exp_table1_q3 );

    SC_METHOD(thread_add_ln746_2_fu_626_p2);
    sensitive << ( exp_table1_q4 );
    sensitive << ( exp_table1_q5 );

    SC_METHOD(thread_add_ln746_3_fu_666_p2);
    sensitive << ( exp_table1_q6 );
    sensitive << ( exp_table1_q7 );

    SC_METHOD(thread_add_ln746_fu_524_p2);
    sensitive << ( exp_table1_q0 );
    sensitive << ( exp_table1_q1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_idle_pp0_0to2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to2 );

    SC_METHOD(thread_exp_table1_address0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln251_fu_370_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_exp_table1_address1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_1_fu_385_p1 );

    SC_METHOD(thread_exp_table1_address2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_2_fu_400_p1 );

    SC_METHOD(thread_exp_table1_address3);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_3_fu_415_p1 );

    SC_METHOD(thread_exp_table1_address4);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_4_fu_430_p1 );

    SC_METHOD(thread_exp_table1_address5);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_5_fu_445_p1 );

    SC_METHOD(thread_exp_table1_address6);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_6_fu_460_p1 );

    SC_METHOD(thread_exp_table1_address7);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_7_fu_475_p1 );

    SC_METHOD(thread_exp_table1_address8);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_8_fu_490_p1 );

    SC_METHOD(thread_exp_table1_address9);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_9_fu_505_p1 );

    SC_METHOD(thread_exp_table1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce3);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce4);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce5);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce6);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce7);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce8);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table1_ce9);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_invert_table2_address0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln259_fu_846_p1 );

    SC_METHOD(thread_invert_table2_ce0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_lhs_V_fu_748_p1);
    sensitive << ( p_Val2_44_reg_1157 );

    SC_METHOD(thread_mul_ln1118_1_fu_992_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_1_fu_992_p00 );

    SC_METHOD(thread_mul_ln1118_1_fu_992_p00);
    sensitive << ( exp_res_1_V_reg_1110_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_1_fu_992_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_2_fu_999_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_2_fu_999_p00 );

    SC_METHOD(thread_mul_ln1118_2_fu_999_p00);
    sensitive << ( exp_res_2_V_reg_1115_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_2_fu_999_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_3_fu_1006_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_3_fu_1006_p00 );

    SC_METHOD(thread_mul_ln1118_3_fu_1006_p00);
    sensitive << ( exp_res_3_V_reg_1120_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_3_fu_1006_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_4_fu_1013_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_4_fu_1013_p00 );

    SC_METHOD(thread_mul_ln1118_4_fu_1013_p00);
    sensitive << ( exp_res_4_V_reg_1125_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_4_fu_1013_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_5_fu_1020_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_5_fu_1020_p00 );

    SC_METHOD(thread_mul_ln1118_5_fu_1020_p00);
    sensitive << ( exp_res_5_V_reg_1130_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_5_fu_1020_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_6_fu_1027_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_6_fu_1027_p00 );

    SC_METHOD(thread_mul_ln1118_6_fu_1027_p00);
    sensitive << ( exp_res_6_V_reg_1135_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_6_fu_1027_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_7_fu_1034_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_7_fu_1034_p00 );

    SC_METHOD(thread_mul_ln1118_7_fu_1034_p00);
    sensitive << ( exp_res_7_V_reg_1140_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_7_fu_1034_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_8_fu_1041_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_8_fu_1041_p00 );

    SC_METHOD(thread_mul_ln1118_8_fu_1041_p00);
    sensitive << ( exp_res_8_V_reg_1145_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_8_fu_1041_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_9_fu_1048_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_9_fu_1048_p00 );

    SC_METHOD(thread_mul_ln1118_9_fu_1048_p00);
    sensitive << ( exp_res_9_V_reg_1151_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_9_fu_1048_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_mul_ln1118_fu_985_p0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_fu_985_p00 );

    SC_METHOD(thread_mul_ln1118_fu_985_p00);
    sensitive << ( exp_res_0_V_reg_1105_pp0_iter2_reg );

    SC_METHOD(thread_mul_ln1118_fu_985_p1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_fu_851_p1 );

    SC_METHOD(thread_or_ln340_fu_806_p2);
    sensitive << ( p_Result_28_fu_774_p3 );
    sensitive << ( xor_ln340_1_fu_800_p2 );

    SC_METHOD(thread_p_Result_21_fu_570_p3);
    sensitive << ( p_Val2_25_fu_558_p2 );

    SC_METHOD(thread_p_Result_22_fu_596_p3);
    sensitive << ( p_Val2_28_fu_590_p2 );

    SC_METHOD(thread_p_Result_23_fu_632_p3);
    sensitive << ( p_Val2_31_fu_620_p2 );

    SC_METHOD(thread_p_Result_24_fu_672_p3);
    sensitive << ( p_Val2_34_fu_660_p2 );

    SC_METHOD(thread_p_Result_25_fu_698_p3);
    sensitive << ( p_Val2_37_fu_692_p2 );

    SC_METHOD(thread_p_Result_26_fu_720_p3);
    sensitive << ( p_Val2_40_fu_714_p2 );

    SC_METHOD(thread_p_Result_27_fu_761_p3);
    sensitive << ( ret_V_1_fu_755_p2 );

    SC_METHOD(thread_p_Result_28_fu_774_p3);
    sensitive << ( p_Val2_46_fu_769_p2 );

    SC_METHOD(thread_p_Result_s_fu_530_p3);
    sensitive << ( p_Val2_22_fu_518_p2 );

    SC_METHOD(thread_p_Val2_22_fu_518_p2);
    sensitive << ( zext_ln44_2_fu_510_p1 );
    sensitive << ( zext_ln44_3_fu_514_p1 );

    SC_METHOD(thread_p_Val2_25_fu_558_p2);
    sensitive << ( zext_ln44_4_fu_550_p1 );
    sensitive << ( zext_ln44_5_fu_554_p1 );

    SC_METHOD(thread_p_Val2_26_fu_538_p3);
    sensitive << ( p_Result_s_fu_530_p3 );
    sensitive << ( add_ln746_fu_524_p2 );

    SC_METHOD(thread_p_Val2_27_fu_578_p3);
    sensitive << ( p_Result_21_fu_570_p3 );
    sensitive << ( add_ln746_1_fu_564_p2 );

    SC_METHOD(thread_p_Val2_28_fu_590_p2);
    sensitive << ( zext_ln785_1_fu_586_p1 );
    sensitive << ( zext_ln785_fu_546_p1 );

    SC_METHOD(thread_p_Val2_31_fu_620_p2);
    sensitive << ( zext_ln44_6_fu_612_p1 );
    sensitive << ( zext_ln44_7_fu_616_p1 );

    SC_METHOD(thread_p_Val2_34_fu_660_p2);
    sensitive << ( zext_ln44_8_fu_652_p1 );
    sensitive << ( zext_ln44_9_fu_656_p1 );

    SC_METHOD(thread_p_Val2_35_fu_640_p3);
    sensitive << ( p_Result_23_fu_632_p3 );
    sensitive << ( add_ln746_2_fu_626_p2 );

    SC_METHOD(thread_p_Val2_36_fu_680_p3);
    sensitive << ( p_Result_24_fu_672_p3 );
    sensitive << ( add_ln746_3_fu_666_p2 );

    SC_METHOD(thread_p_Val2_37_fu_692_p2);
    sensitive << ( zext_ln785_3_fu_688_p1 );
    sensitive << ( zext_ln785_2_fu_648_p1 );

    SC_METHOD(thread_p_Val2_38_fu_604_p3);
    sensitive << ( p_Val2_28_fu_590_p2 );
    sensitive << ( p_Result_22_fu_596_p3 );

    SC_METHOD(thread_p_Val2_39_fu_706_p3);
    sensitive << ( p_Val2_37_fu_692_p2 );
    sensitive << ( p_Result_25_fu_698_p3 );

    SC_METHOD(thread_p_Val2_40_fu_714_p2);
    sensitive << ( p_Val2_39_fu_706_p3 );
    sensitive << ( p_Val2_38_fu_604_p3 );

    SC_METHOD(thread_p_Val2_44_fu_728_p3);
    sensitive << ( p_Val2_40_fu_714_p2 );
    sensitive << ( p_Result_26_fu_720_p3 );

    SC_METHOD(thread_p_Val2_46_fu_769_p2);
    sensitive << ( p_Val2_44_reg_1157 );
    sensitive << ( ret_V_fu_742_p2 );

    SC_METHOD(thread_res_0_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_fu_985_p2 );

    SC_METHOD(thread_res_0_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_1_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_1_fu_992_p2 );

    SC_METHOD(thread_res_1_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_2_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_2_fu_999_p2 );

    SC_METHOD(thread_res_2_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_3_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_3_fu_1006_p2 );

    SC_METHOD(thread_res_3_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_4_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_4_fu_1013_p2 );

    SC_METHOD(thread_res_4_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_5_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_5_fu_1020_p2 );

    SC_METHOD(thread_res_5_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_6_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_6_fu_1027_p2 );

    SC_METHOD(thread_res_6_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_7_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_7_fu_1034_p2 );

    SC_METHOD(thread_res_7_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_8_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_8_fu_1041_p2 );

    SC_METHOD(thread_res_8_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_9_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( mul_ln1118_9_fu_1048_p2 );

    SC_METHOD(thread_res_9_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ret_V_1_fu_755_p2);
    sensitive << ( lhs_V_fu_748_p1 );
    sensitive << ( rhs_V_fu_751_p1 );

    SC_METHOD(thread_ret_V_fu_742_p2);
    sensitive << ( zext_ln44_1_fu_739_p1 );
    sensitive << ( zext_ln44_fu_736_p1 );

    SC_METHOD(thread_rhs_V_fu_751_p1);
    sensitive << ( ret_V_fu_742_p2 );

    SC_METHOD(thread_select_ln340_fu_822_p3);
    sensitive << ( xor_ln340_fu_794_p2 );
    sensitive << ( tmp_fu_812_p4 );

    SC_METHOD(thread_select_ln388_fu_830_p3);
    sensitive << ( tmp_fu_812_p4 );
    sensitive << ( underflow_fu_788_p2 );

    SC_METHOD(thread_sext_ln1116_fu_851_p1);
    sensitive << ( invert_table2_q0 );

    SC_METHOD(thread_tmp_fu_812_p4);
    sensitive << ( p_Val2_46_fu_769_p2 );

    SC_METHOD(thread_underflow_fu_788_p2);
    sensitive << ( p_Result_27_fu_761_p3 );
    sensitive << ( xor_ln786_fu_782_p2 );

    SC_METHOD(thread_xor_ln340_1_fu_800_p2);
    sensitive << ( p_Result_27_fu_761_p3 );

    SC_METHOD(thread_xor_ln340_fu_794_p2);
    sensitive << ( p_Result_28_fu_774_p3 );
    sensitive << ( p_Result_27_fu_761_p3 );

    SC_METHOD(thread_xor_ln786_fu_782_p2);
    sensitive << ( p_Result_28_fu_774_p3 );

    SC_METHOD(thread_y_V_10_fu_838_p3);
    sensitive << ( or_ln340_fu_806_p2 );
    sensitive << ( select_ln340_fu_822_p3 );
    sensitive << ( select_ln388_fu_830_p3 );

    SC_METHOD(thread_y_V_1_fu_375_p4);
    sensitive << ( data_1_V );

    SC_METHOD(thread_y_V_2_fu_390_p4);
    sensitive << ( data_2_V );

    SC_METHOD(thread_y_V_3_fu_405_p4);
    sensitive << ( data_3_V );

    SC_METHOD(thread_y_V_4_fu_420_p4);
    sensitive << ( data_4_V );

    SC_METHOD(thread_y_V_5_fu_435_p4);
    sensitive << ( data_5_V );

    SC_METHOD(thread_y_V_6_fu_450_p4);
    sensitive << ( data_6_V );

    SC_METHOD(thread_y_V_7_fu_465_p4);
    sensitive << ( data_7_V );

    SC_METHOD(thread_y_V_8_fu_480_p4);
    sensitive << ( data_8_V );

    SC_METHOD(thread_y_V_9_fu_495_p4);
    sensitive << ( data_9_V );

    SC_METHOD(thread_y_V_fu_360_p4);
    sensitive << ( data_0_V );

    SC_METHOD(thread_zext_ln251_1_fu_385_p1);
    sensitive << ( y_V_1_fu_375_p4 );

    SC_METHOD(thread_zext_ln251_2_fu_400_p1);
    sensitive << ( y_V_2_fu_390_p4 );

    SC_METHOD(thread_zext_ln251_3_fu_415_p1);
    sensitive << ( y_V_3_fu_405_p4 );

    SC_METHOD(thread_zext_ln251_4_fu_430_p1);
    sensitive << ( y_V_4_fu_420_p4 );

    SC_METHOD(thread_zext_ln251_5_fu_445_p1);
    sensitive << ( y_V_5_fu_435_p4 );

    SC_METHOD(thread_zext_ln251_6_fu_460_p1);
    sensitive << ( y_V_6_fu_450_p4 );

    SC_METHOD(thread_zext_ln251_7_fu_475_p1);
    sensitive << ( y_V_7_fu_465_p4 );

    SC_METHOD(thread_zext_ln251_8_fu_490_p1);
    sensitive << ( y_V_8_fu_480_p4 );

    SC_METHOD(thread_zext_ln251_9_fu_505_p1);
    sensitive << ( y_V_9_fu_495_p4 );

    SC_METHOD(thread_zext_ln251_fu_370_p1);
    sensitive << ( y_V_fu_360_p4 );

    SC_METHOD(thread_zext_ln259_fu_846_p1);
    sensitive << ( y_V_10_fu_838_p3 );

    SC_METHOD(thread_zext_ln44_1_fu_739_p1);
    sensitive << ( exp_res_8_V_reg_1145 );

    SC_METHOD(thread_zext_ln44_2_fu_510_p1);
    sensitive << ( exp_table1_q1 );

    SC_METHOD(thread_zext_ln44_3_fu_514_p1);
    sensitive << ( exp_table1_q0 );

    SC_METHOD(thread_zext_ln44_4_fu_550_p1);
    sensitive << ( exp_table1_q3 );

    SC_METHOD(thread_zext_ln44_5_fu_554_p1);
    sensitive << ( exp_table1_q2 );

    SC_METHOD(thread_zext_ln44_6_fu_612_p1);
    sensitive << ( exp_table1_q5 );

    SC_METHOD(thread_zext_ln44_7_fu_616_p1);
    sensitive << ( exp_table1_q4 );

    SC_METHOD(thread_zext_ln44_8_fu_652_p1);
    sensitive << ( exp_table1_q7 );

    SC_METHOD(thread_zext_ln44_9_fu_656_p1);
    sensitive << ( exp_table1_q6 );

    SC_METHOD(thread_zext_ln44_fu_736_p1);
    sensitive << ( exp_res_9_V_reg_1151 );

    SC_METHOD(thread_zext_ln785_1_fu_586_p1);
    sensitive << ( p_Val2_27_fu_578_p3 );

    SC_METHOD(thread_zext_ln785_2_fu_648_p1);
    sensitive << ( p_Val2_35_fu_640_p3 );

    SC_METHOD(thread_zext_ln785_3_fu_688_p1);
    sensitive << ( p_Val2_36_fu_680_p3 );

    SC_METHOD(thread_zext_ln785_fu_546_p1);
    sensitive << ( p_Val2_26_fu_538_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "softmax_latency_ap_fixed_ap_fixed_softmax_config10_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V, "(port)data_0_V");
    sc_trace(mVcdFile, data_1_V, "(port)data_1_V");
    sc_trace(mVcdFile, data_2_V, "(port)data_2_V");
    sc_trace(mVcdFile, data_3_V, "(port)data_3_V");
    sc_trace(mVcdFile, data_4_V, "(port)data_4_V");
    sc_trace(mVcdFile, data_5_V, "(port)data_5_V");
    sc_trace(mVcdFile, data_6_V, "(port)data_6_V");
    sc_trace(mVcdFile, data_7_V, "(port)data_7_V");
    sc_trace(mVcdFile, data_8_V, "(port)data_8_V");
    sc_trace(mVcdFile, data_9_V, "(port)data_9_V");
    sc_trace(mVcdFile, res_0_V, "(port)res_0_V");
    sc_trace(mVcdFile, res_0_V_ap_vld, "(port)res_0_V_ap_vld");
    sc_trace(mVcdFile, res_1_V, "(port)res_1_V");
    sc_trace(mVcdFile, res_1_V_ap_vld, "(port)res_1_V_ap_vld");
    sc_trace(mVcdFile, res_2_V, "(port)res_2_V");
    sc_trace(mVcdFile, res_2_V_ap_vld, "(port)res_2_V_ap_vld");
    sc_trace(mVcdFile, res_3_V, "(port)res_3_V");
    sc_trace(mVcdFile, res_3_V_ap_vld, "(port)res_3_V_ap_vld");
    sc_trace(mVcdFile, res_4_V, "(port)res_4_V");
    sc_trace(mVcdFile, res_4_V_ap_vld, "(port)res_4_V_ap_vld");
    sc_trace(mVcdFile, res_5_V, "(port)res_5_V");
    sc_trace(mVcdFile, res_5_V_ap_vld, "(port)res_5_V_ap_vld");
    sc_trace(mVcdFile, res_6_V, "(port)res_6_V");
    sc_trace(mVcdFile, res_6_V_ap_vld, "(port)res_6_V_ap_vld");
    sc_trace(mVcdFile, res_7_V, "(port)res_7_V");
    sc_trace(mVcdFile, res_7_V_ap_vld, "(port)res_7_V_ap_vld");
    sc_trace(mVcdFile, res_8_V, "(port)res_8_V");
    sc_trace(mVcdFile, res_8_V_ap_vld, "(port)res_8_V_ap_vld");
    sc_trace(mVcdFile, res_9_V, "(port)res_9_V");
    sc_trace(mVcdFile, res_9_V_ap_vld, "(port)res_9_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exp_table1_address0, "exp_table1_address0");
    sc_trace(mVcdFile, exp_table1_ce0, "exp_table1_ce0");
    sc_trace(mVcdFile, exp_table1_q0, "exp_table1_q0");
    sc_trace(mVcdFile, exp_table1_address1, "exp_table1_address1");
    sc_trace(mVcdFile, exp_table1_ce1, "exp_table1_ce1");
    sc_trace(mVcdFile, exp_table1_q1, "exp_table1_q1");
    sc_trace(mVcdFile, exp_table1_address2, "exp_table1_address2");
    sc_trace(mVcdFile, exp_table1_ce2, "exp_table1_ce2");
    sc_trace(mVcdFile, exp_table1_q2, "exp_table1_q2");
    sc_trace(mVcdFile, exp_table1_address3, "exp_table1_address3");
    sc_trace(mVcdFile, exp_table1_ce3, "exp_table1_ce3");
    sc_trace(mVcdFile, exp_table1_q3, "exp_table1_q3");
    sc_trace(mVcdFile, exp_table1_address4, "exp_table1_address4");
    sc_trace(mVcdFile, exp_table1_ce4, "exp_table1_ce4");
    sc_trace(mVcdFile, exp_table1_q4, "exp_table1_q4");
    sc_trace(mVcdFile, exp_table1_address5, "exp_table1_address5");
    sc_trace(mVcdFile, exp_table1_ce5, "exp_table1_ce5");
    sc_trace(mVcdFile, exp_table1_q5, "exp_table1_q5");
    sc_trace(mVcdFile, exp_table1_address6, "exp_table1_address6");
    sc_trace(mVcdFile, exp_table1_ce6, "exp_table1_ce6");
    sc_trace(mVcdFile, exp_table1_q6, "exp_table1_q6");
    sc_trace(mVcdFile, exp_table1_address7, "exp_table1_address7");
    sc_trace(mVcdFile, exp_table1_ce7, "exp_table1_ce7");
    sc_trace(mVcdFile, exp_table1_q7, "exp_table1_q7");
    sc_trace(mVcdFile, exp_table1_address8, "exp_table1_address8");
    sc_trace(mVcdFile, exp_table1_ce8, "exp_table1_ce8");
    sc_trace(mVcdFile, exp_table1_q8, "exp_table1_q8");
    sc_trace(mVcdFile, exp_table1_address9, "exp_table1_address9");
    sc_trace(mVcdFile, exp_table1_ce9, "exp_table1_ce9");
    sc_trace(mVcdFile, exp_table1_q9, "exp_table1_q9");
    sc_trace(mVcdFile, invert_table2_address0, "invert_table2_address0");
    sc_trace(mVcdFile, invert_table2_ce0, "invert_table2_ce0");
    sc_trace(mVcdFile, invert_table2_q0, "invert_table2_q0");
    sc_trace(mVcdFile, exp_res_0_V_reg_1105, "exp_res_0_V_reg_1105");
    sc_trace(mVcdFile, exp_res_0_V_reg_1105_pp0_iter2_reg, "exp_res_0_V_reg_1105_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_1110, "exp_res_1_V_reg_1110");
    sc_trace(mVcdFile, exp_res_1_V_reg_1110_pp0_iter2_reg, "exp_res_1_V_reg_1110_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_1115, "exp_res_2_V_reg_1115");
    sc_trace(mVcdFile, exp_res_2_V_reg_1115_pp0_iter2_reg, "exp_res_2_V_reg_1115_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_3_V_reg_1120, "exp_res_3_V_reg_1120");
    sc_trace(mVcdFile, exp_res_3_V_reg_1120_pp0_iter2_reg, "exp_res_3_V_reg_1120_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_4_V_reg_1125, "exp_res_4_V_reg_1125");
    sc_trace(mVcdFile, exp_res_4_V_reg_1125_pp0_iter2_reg, "exp_res_4_V_reg_1125_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_5_V_reg_1130, "exp_res_5_V_reg_1130");
    sc_trace(mVcdFile, exp_res_5_V_reg_1130_pp0_iter2_reg, "exp_res_5_V_reg_1130_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_6_V_reg_1135, "exp_res_6_V_reg_1135");
    sc_trace(mVcdFile, exp_res_6_V_reg_1135_pp0_iter2_reg, "exp_res_6_V_reg_1135_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_7_V_reg_1140, "exp_res_7_V_reg_1140");
    sc_trace(mVcdFile, exp_res_7_V_reg_1140_pp0_iter2_reg, "exp_res_7_V_reg_1140_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_8_V_reg_1145, "exp_res_8_V_reg_1145");
    sc_trace(mVcdFile, exp_res_8_V_reg_1145_pp0_iter2_reg, "exp_res_8_V_reg_1145_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_9_V_reg_1151, "exp_res_9_V_reg_1151");
    sc_trace(mVcdFile, exp_res_9_V_reg_1151_pp0_iter2_reg, "exp_res_9_V_reg_1151_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Val2_44_fu_728_p3, "p_Val2_44_fu_728_p3");
    sc_trace(mVcdFile, p_Val2_44_reg_1157, "p_Val2_44_reg_1157");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, zext_ln251_fu_370_p1, "zext_ln251_fu_370_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln251_1_fu_385_p1, "zext_ln251_1_fu_385_p1");
    sc_trace(mVcdFile, zext_ln251_2_fu_400_p1, "zext_ln251_2_fu_400_p1");
    sc_trace(mVcdFile, zext_ln251_3_fu_415_p1, "zext_ln251_3_fu_415_p1");
    sc_trace(mVcdFile, zext_ln251_4_fu_430_p1, "zext_ln251_4_fu_430_p1");
    sc_trace(mVcdFile, zext_ln251_5_fu_445_p1, "zext_ln251_5_fu_445_p1");
    sc_trace(mVcdFile, zext_ln251_6_fu_460_p1, "zext_ln251_6_fu_460_p1");
    sc_trace(mVcdFile, zext_ln251_7_fu_475_p1, "zext_ln251_7_fu_475_p1");
    sc_trace(mVcdFile, zext_ln251_8_fu_490_p1, "zext_ln251_8_fu_490_p1");
    sc_trace(mVcdFile, zext_ln251_9_fu_505_p1, "zext_ln251_9_fu_505_p1");
    sc_trace(mVcdFile, zext_ln259_fu_846_p1, "zext_ln259_fu_846_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, y_V_fu_360_p4, "y_V_fu_360_p4");
    sc_trace(mVcdFile, y_V_1_fu_375_p4, "y_V_1_fu_375_p4");
    sc_trace(mVcdFile, y_V_2_fu_390_p4, "y_V_2_fu_390_p4");
    sc_trace(mVcdFile, y_V_3_fu_405_p4, "y_V_3_fu_405_p4");
    sc_trace(mVcdFile, y_V_4_fu_420_p4, "y_V_4_fu_420_p4");
    sc_trace(mVcdFile, y_V_5_fu_435_p4, "y_V_5_fu_435_p4");
    sc_trace(mVcdFile, y_V_6_fu_450_p4, "y_V_6_fu_450_p4");
    sc_trace(mVcdFile, y_V_7_fu_465_p4, "y_V_7_fu_465_p4");
    sc_trace(mVcdFile, y_V_8_fu_480_p4, "y_V_8_fu_480_p4");
    sc_trace(mVcdFile, y_V_9_fu_495_p4, "y_V_9_fu_495_p4");
    sc_trace(mVcdFile, zext_ln44_2_fu_510_p1, "zext_ln44_2_fu_510_p1");
    sc_trace(mVcdFile, zext_ln44_3_fu_514_p1, "zext_ln44_3_fu_514_p1");
    sc_trace(mVcdFile, p_Val2_22_fu_518_p2, "p_Val2_22_fu_518_p2");
    sc_trace(mVcdFile, p_Result_s_fu_530_p3, "p_Result_s_fu_530_p3");
    sc_trace(mVcdFile, add_ln746_fu_524_p2, "add_ln746_fu_524_p2");
    sc_trace(mVcdFile, p_Val2_26_fu_538_p3, "p_Val2_26_fu_538_p3");
    sc_trace(mVcdFile, zext_ln44_4_fu_550_p1, "zext_ln44_4_fu_550_p1");
    sc_trace(mVcdFile, zext_ln44_5_fu_554_p1, "zext_ln44_5_fu_554_p1");
    sc_trace(mVcdFile, p_Val2_25_fu_558_p2, "p_Val2_25_fu_558_p2");
    sc_trace(mVcdFile, p_Result_21_fu_570_p3, "p_Result_21_fu_570_p3");
    sc_trace(mVcdFile, add_ln746_1_fu_564_p2, "add_ln746_1_fu_564_p2");
    sc_trace(mVcdFile, p_Val2_27_fu_578_p3, "p_Val2_27_fu_578_p3");
    sc_trace(mVcdFile, zext_ln785_1_fu_586_p1, "zext_ln785_1_fu_586_p1");
    sc_trace(mVcdFile, zext_ln785_fu_546_p1, "zext_ln785_fu_546_p1");
    sc_trace(mVcdFile, p_Val2_28_fu_590_p2, "p_Val2_28_fu_590_p2");
    sc_trace(mVcdFile, p_Result_22_fu_596_p3, "p_Result_22_fu_596_p3");
    sc_trace(mVcdFile, zext_ln44_6_fu_612_p1, "zext_ln44_6_fu_612_p1");
    sc_trace(mVcdFile, zext_ln44_7_fu_616_p1, "zext_ln44_7_fu_616_p1");
    sc_trace(mVcdFile, p_Val2_31_fu_620_p2, "p_Val2_31_fu_620_p2");
    sc_trace(mVcdFile, p_Result_23_fu_632_p3, "p_Result_23_fu_632_p3");
    sc_trace(mVcdFile, add_ln746_2_fu_626_p2, "add_ln746_2_fu_626_p2");
    sc_trace(mVcdFile, p_Val2_35_fu_640_p3, "p_Val2_35_fu_640_p3");
    sc_trace(mVcdFile, zext_ln44_8_fu_652_p1, "zext_ln44_8_fu_652_p1");
    sc_trace(mVcdFile, zext_ln44_9_fu_656_p1, "zext_ln44_9_fu_656_p1");
    sc_trace(mVcdFile, p_Val2_34_fu_660_p2, "p_Val2_34_fu_660_p2");
    sc_trace(mVcdFile, p_Result_24_fu_672_p3, "p_Result_24_fu_672_p3");
    sc_trace(mVcdFile, add_ln746_3_fu_666_p2, "add_ln746_3_fu_666_p2");
    sc_trace(mVcdFile, p_Val2_36_fu_680_p3, "p_Val2_36_fu_680_p3");
    sc_trace(mVcdFile, zext_ln785_3_fu_688_p1, "zext_ln785_3_fu_688_p1");
    sc_trace(mVcdFile, zext_ln785_2_fu_648_p1, "zext_ln785_2_fu_648_p1");
    sc_trace(mVcdFile, p_Val2_37_fu_692_p2, "p_Val2_37_fu_692_p2");
    sc_trace(mVcdFile, p_Result_25_fu_698_p3, "p_Result_25_fu_698_p3");
    sc_trace(mVcdFile, p_Val2_39_fu_706_p3, "p_Val2_39_fu_706_p3");
    sc_trace(mVcdFile, p_Val2_38_fu_604_p3, "p_Val2_38_fu_604_p3");
    sc_trace(mVcdFile, p_Val2_40_fu_714_p2, "p_Val2_40_fu_714_p2");
    sc_trace(mVcdFile, p_Result_26_fu_720_p3, "p_Result_26_fu_720_p3");
    sc_trace(mVcdFile, zext_ln44_1_fu_739_p1, "zext_ln44_1_fu_739_p1");
    sc_trace(mVcdFile, zext_ln44_fu_736_p1, "zext_ln44_fu_736_p1");
    sc_trace(mVcdFile, ret_V_fu_742_p2, "ret_V_fu_742_p2");
    sc_trace(mVcdFile, lhs_V_fu_748_p1, "lhs_V_fu_748_p1");
    sc_trace(mVcdFile, rhs_V_fu_751_p1, "rhs_V_fu_751_p1");
    sc_trace(mVcdFile, ret_V_1_fu_755_p2, "ret_V_1_fu_755_p2");
    sc_trace(mVcdFile, p_Val2_46_fu_769_p2, "p_Val2_46_fu_769_p2");
    sc_trace(mVcdFile, p_Result_28_fu_774_p3, "p_Result_28_fu_774_p3");
    sc_trace(mVcdFile, p_Result_27_fu_761_p3, "p_Result_27_fu_761_p3");
    sc_trace(mVcdFile, xor_ln786_fu_782_p2, "xor_ln786_fu_782_p2");
    sc_trace(mVcdFile, xor_ln340_1_fu_800_p2, "xor_ln340_1_fu_800_p2");
    sc_trace(mVcdFile, xor_ln340_fu_794_p2, "xor_ln340_fu_794_p2");
    sc_trace(mVcdFile, tmp_fu_812_p4, "tmp_fu_812_p4");
    sc_trace(mVcdFile, underflow_fu_788_p2, "underflow_fu_788_p2");
    sc_trace(mVcdFile, or_ln340_fu_806_p2, "or_ln340_fu_806_p2");
    sc_trace(mVcdFile, select_ln340_fu_822_p3, "select_ln340_fu_822_p3");
    sc_trace(mVcdFile, select_ln388_fu_830_p3, "select_ln388_fu_830_p3");
    sc_trace(mVcdFile, y_V_10_fu_838_p3, "y_V_10_fu_838_p3");
    sc_trace(mVcdFile, mul_ln1118_fu_985_p2, "mul_ln1118_fu_985_p2");
    sc_trace(mVcdFile, mul_ln1118_1_fu_992_p2, "mul_ln1118_1_fu_992_p2");
    sc_trace(mVcdFile, mul_ln1118_2_fu_999_p2, "mul_ln1118_2_fu_999_p2");
    sc_trace(mVcdFile, mul_ln1118_3_fu_1006_p2, "mul_ln1118_3_fu_1006_p2");
    sc_trace(mVcdFile, mul_ln1118_4_fu_1013_p2, "mul_ln1118_4_fu_1013_p2");
    sc_trace(mVcdFile, mul_ln1118_5_fu_1020_p2, "mul_ln1118_5_fu_1020_p2");
    sc_trace(mVcdFile, mul_ln1118_6_fu_1027_p2, "mul_ln1118_6_fu_1027_p2");
    sc_trace(mVcdFile, mul_ln1118_7_fu_1034_p2, "mul_ln1118_7_fu_1034_p2");
    sc_trace(mVcdFile, mul_ln1118_8_fu_1041_p2, "mul_ln1118_8_fu_1041_p2");
    sc_trace(mVcdFile, mul_ln1118_9_fu_1048_p2, "mul_ln1118_9_fu_1048_p2");
    sc_trace(mVcdFile, mul_ln1118_fu_985_p0, "mul_ln1118_fu_985_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_985_p1, "mul_ln1118_fu_985_p1");
    sc_trace(mVcdFile, sext_ln1116_fu_851_p1, "sext_ln1116_fu_851_p1");
    sc_trace(mVcdFile, mul_ln1118_1_fu_992_p0, "mul_ln1118_1_fu_992_p0");
    sc_trace(mVcdFile, mul_ln1118_1_fu_992_p1, "mul_ln1118_1_fu_992_p1");
    sc_trace(mVcdFile, mul_ln1118_2_fu_999_p0, "mul_ln1118_2_fu_999_p0");
    sc_trace(mVcdFile, mul_ln1118_2_fu_999_p1, "mul_ln1118_2_fu_999_p1");
    sc_trace(mVcdFile, mul_ln1118_3_fu_1006_p0, "mul_ln1118_3_fu_1006_p0");
    sc_trace(mVcdFile, mul_ln1118_3_fu_1006_p1, "mul_ln1118_3_fu_1006_p1");
    sc_trace(mVcdFile, mul_ln1118_4_fu_1013_p0, "mul_ln1118_4_fu_1013_p0");
    sc_trace(mVcdFile, mul_ln1118_4_fu_1013_p1, "mul_ln1118_4_fu_1013_p1");
    sc_trace(mVcdFile, mul_ln1118_5_fu_1020_p0, "mul_ln1118_5_fu_1020_p0");
    sc_trace(mVcdFile, mul_ln1118_5_fu_1020_p1, "mul_ln1118_5_fu_1020_p1");
    sc_trace(mVcdFile, mul_ln1118_6_fu_1027_p0, "mul_ln1118_6_fu_1027_p0");
    sc_trace(mVcdFile, mul_ln1118_6_fu_1027_p1, "mul_ln1118_6_fu_1027_p1");
    sc_trace(mVcdFile, mul_ln1118_7_fu_1034_p0, "mul_ln1118_7_fu_1034_p0");
    sc_trace(mVcdFile, mul_ln1118_7_fu_1034_p1, "mul_ln1118_7_fu_1034_p1");
    sc_trace(mVcdFile, mul_ln1118_8_fu_1041_p0, "mul_ln1118_8_fu_1041_p0");
    sc_trace(mVcdFile, mul_ln1118_8_fu_1041_p1, "mul_ln1118_8_fu_1041_p1");
    sc_trace(mVcdFile, mul_ln1118_9_fu_1048_p0, "mul_ln1118_9_fu_1048_p0");
    sc_trace(mVcdFile, mul_ln1118_9_fu_1048_p1, "mul_ln1118_9_fu_1048_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to2, "ap_idle_pp0_0to2");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, mul_ln1118_1_fu_992_p00, "mul_ln1118_1_fu_992_p00");
    sc_trace(mVcdFile, mul_ln1118_2_fu_999_p00, "mul_ln1118_2_fu_999_p00");
    sc_trace(mVcdFile, mul_ln1118_3_fu_1006_p00, "mul_ln1118_3_fu_1006_p00");
    sc_trace(mVcdFile, mul_ln1118_4_fu_1013_p00, "mul_ln1118_4_fu_1013_p00");
    sc_trace(mVcdFile, mul_ln1118_5_fu_1020_p00, "mul_ln1118_5_fu_1020_p00");
    sc_trace(mVcdFile, mul_ln1118_6_fu_1027_p00, "mul_ln1118_6_fu_1027_p00");
    sc_trace(mVcdFile, mul_ln1118_7_fu_1034_p00, "mul_ln1118_7_fu_1034_p00");
    sc_trace(mVcdFile, mul_ln1118_8_fu_1041_p00, "mul_ln1118_8_fu_1041_p00");
    sc_trace(mVcdFile, mul_ln1118_9_fu_1048_p00, "mul_ln1118_9_fu_1048_p00");
    sc_trace(mVcdFile, mul_ln1118_fu_985_p00, "mul_ln1118_fu_985_p00");
#endif

    }
}

softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::~softmax_latency_ap_fixed_ap_fixed_softmax_config10_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete exp_table1_U;
    delete invert_table2_U;
    delete myproject_mul_mul_17ns_18s_26_1_1_U861;
    delete myproject_mul_mul_17ns_18s_26_1_1_U862;
    delete myproject_mul_mul_17ns_18s_26_1_1_U863;
    delete myproject_mul_mul_17ns_18s_26_1_1_U864;
    delete myproject_mul_mul_17ns_18s_26_1_1_U865;
    delete myproject_mul_mul_17ns_18s_26_1_1_U866;
    delete myproject_mul_mul_17ns_18s_26_1_1_U867;
    delete myproject_mul_mul_17ns_18s_26_1_1_U868;
    delete myproject_mul_mul_17ns_18s_26_1_1_U869;
    delete myproject_mul_mul_17ns_18s_26_1_1_U870;
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_res_0_V_reg_1105 = exp_table1_q0.read();
        exp_res_1_V_reg_1110 = exp_table1_q1.read();
        exp_res_2_V_reg_1115 = exp_table1_q2.read();
        exp_res_3_V_reg_1120 = exp_table1_q3.read();
        exp_res_4_V_reg_1125 = exp_table1_q4.read();
        exp_res_5_V_reg_1130 = exp_table1_q5.read();
        exp_res_6_V_reg_1135 = exp_table1_q6.read();
        exp_res_7_V_reg_1140 = exp_table1_q7.read();
        exp_res_8_V_reg_1145 = exp_table1_q8.read();
        exp_res_9_V_reg_1151 = exp_table1_q9.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exp_res_0_V_reg_1105_pp0_iter2_reg = exp_res_0_V_reg_1105.read();
        exp_res_1_V_reg_1110_pp0_iter2_reg = exp_res_1_V_reg_1110.read();
        exp_res_2_V_reg_1115_pp0_iter2_reg = exp_res_2_V_reg_1115.read();
        exp_res_3_V_reg_1120_pp0_iter2_reg = exp_res_3_V_reg_1120.read();
        exp_res_4_V_reg_1125_pp0_iter2_reg = exp_res_4_V_reg_1125.read();
        exp_res_5_V_reg_1130_pp0_iter2_reg = exp_res_5_V_reg_1130.read();
        exp_res_6_V_reg_1135_pp0_iter2_reg = exp_res_6_V_reg_1135.read();
        exp_res_7_V_reg_1140_pp0_iter2_reg = exp_res_7_V_reg_1140.read();
        exp_res_8_V_reg_1145_pp0_iter2_reg = exp_res_8_V_reg_1145.read();
        exp_res_9_V_reg_1151_pp0_iter2_reg = exp_res_9_V_reg_1151.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_Val2_44_reg_1157 = p_Val2_44_fu_728_p3.read();
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_add_ln746_1_fu_564_p2() {
    add_ln746_1_fu_564_p2 = (!exp_table1_q2.read().is_01() || !exp_table1_q3.read().is_01())? sc_lv<17>(): (sc_biguint<17>(exp_table1_q2.read()) + sc_biguint<17>(exp_table1_q3.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_add_ln746_2_fu_626_p2() {
    add_ln746_2_fu_626_p2 = (!exp_table1_q4.read().is_01() || !exp_table1_q5.read().is_01())? sc_lv<17>(): (sc_biguint<17>(exp_table1_q4.read()) + sc_biguint<17>(exp_table1_q5.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_add_ln746_3_fu_666_p2() {
    add_ln746_3_fu_666_p2 = (!exp_table1_q6.read().is_01() || !exp_table1_q7.read().is_01())? sc_lv<17>(): (sc_biguint<17>(exp_table1_q6.read()) + sc_biguint<17>(exp_table1_q7.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_add_ln746_fu_524_p2() {
    add_ln746_fu_524_p2 = (!exp_table1_q0.read().is_01() || !exp_table1_q1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(exp_table1_q0.read()) + sc_biguint<17>(exp_table1_q1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_idle_pp0_0to2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0_0to2 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to2 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to2.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address0() {
    exp_table1_address0 =  (sc_lv<10>) (zext_ln251_fu_370_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address1() {
    exp_table1_address1 =  (sc_lv<10>) (zext_ln251_1_fu_385_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address2() {
    exp_table1_address2 =  (sc_lv<10>) (zext_ln251_2_fu_400_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address3() {
    exp_table1_address3 =  (sc_lv<10>) (zext_ln251_3_fu_415_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address4() {
    exp_table1_address4 =  (sc_lv<10>) (zext_ln251_4_fu_430_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address5() {
    exp_table1_address5 =  (sc_lv<10>) (zext_ln251_5_fu_445_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address6() {
    exp_table1_address6 =  (sc_lv<10>) (zext_ln251_6_fu_460_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address7() {
    exp_table1_address7 =  (sc_lv<10>) (zext_ln251_7_fu_475_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address8() {
    exp_table1_address8 =  (sc_lv<10>) (zext_ln251_8_fu_490_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_address9() {
    exp_table1_address9 =  (sc_lv<10>) (zext_ln251_9_fu_505_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce0 = ap_const_logic_1;
    } else {
        exp_table1_ce0 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce1 = ap_const_logic_1;
    } else {
        exp_table1_ce1 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce2 = ap_const_logic_1;
    } else {
        exp_table1_ce2 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce3 = ap_const_logic_1;
    } else {
        exp_table1_ce3 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce4 = ap_const_logic_1;
    } else {
        exp_table1_ce4 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce5() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce5 = ap_const_logic_1;
    } else {
        exp_table1_ce5 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce6 = ap_const_logic_1;
    } else {
        exp_table1_ce6 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce7() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce7 = ap_const_logic_1;
    } else {
        exp_table1_ce7 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce8() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce8 = ap_const_logic_1;
    } else {
        exp_table1_ce8 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_exp_table1_ce9() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table1_ce9 = ap_const_logic_1;
    } else {
        exp_table1_ce9 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_invert_table2_address0() {
    invert_table2_address0 =  (sc_lv<10>) (zext_ln259_fu_846_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_invert_table2_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        invert_table2_ce0 = ap_const_logic_1;
    } else {
        invert_table2_ce0 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_lhs_V_fu_748_p1() {
    lhs_V_fu_748_p1 = esl_sext<19,18>(p_Val2_44_reg_1157.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_1_fu_992_p0() {
    mul_ln1118_1_fu_992_p0 =  (sc_lv<17>) (mul_ln1118_1_fu_992_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_1_fu_992_p00() {
    mul_ln1118_1_fu_992_p00 = esl_zext<26,17>(exp_res_1_V_reg_1110_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_1_fu_992_p1() {
    mul_ln1118_1_fu_992_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_2_fu_999_p0() {
    mul_ln1118_2_fu_999_p0 =  (sc_lv<17>) (mul_ln1118_2_fu_999_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_2_fu_999_p00() {
    mul_ln1118_2_fu_999_p00 = esl_zext<26,17>(exp_res_2_V_reg_1115_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_2_fu_999_p1() {
    mul_ln1118_2_fu_999_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_3_fu_1006_p0() {
    mul_ln1118_3_fu_1006_p0 =  (sc_lv<17>) (mul_ln1118_3_fu_1006_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_3_fu_1006_p00() {
    mul_ln1118_3_fu_1006_p00 = esl_zext<26,17>(exp_res_3_V_reg_1120_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_3_fu_1006_p1() {
    mul_ln1118_3_fu_1006_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_4_fu_1013_p0() {
    mul_ln1118_4_fu_1013_p0 =  (sc_lv<17>) (mul_ln1118_4_fu_1013_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_4_fu_1013_p00() {
    mul_ln1118_4_fu_1013_p00 = esl_zext<26,17>(exp_res_4_V_reg_1125_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_4_fu_1013_p1() {
    mul_ln1118_4_fu_1013_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_5_fu_1020_p0() {
    mul_ln1118_5_fu_1020_p0 =  (sc_lv<17>) (mul_ln1118_5_fu_1020_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_5_fu_1020_p00() {
    mul_ln1118_5_fu_1020_p00 = esl_zext<26,17>(exp_res_5_V_reg_1130_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_5_fu_1020_p1() {
    mul_ln1118_5_fu_1020_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_6_fu_1027_p0() {
    mul_ln1118_6_fu_1027_p0 =  (sc_lv<17>) (mul_ln1118_6_fu_1027_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_6_fu_1027_p00() {
    mul_ln1118_6_fu_1027_p00 = esl_zext<26,17>(exp_res_6_V_reg_1135_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_6_fu_1027_p1() {
    mul_ln1118_6_fu_1027_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_7_fu_1034_p0() {
    mul_ln1118_7_fu_1034_p0 =  (sc_lv<17>) (mul_ln1118_7_fu_1034_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_7_fu_1034_p00() {
    mul_ln1118_7_fu_1034_p00 = esl_zext<26,17>(exp_res_7_V_reg_1140_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_7_fu_1034_p1() {
    mul_ln1118_7_fu_1034_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_8_fu_1041_p0() {
    mul_ln1118_8_fu_1041_p0 =  (sc_lv<17>) (mul_ln1118_8_fu_1041_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_8_fu_1041_p00() {
    mul_ln1118_8_fu_1041_p00 = esl_zext<26,17>(exp_res_8_V_reg_1145_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_8_fu_1041_p1() {
    mul_ln1118_8_fu_1041_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_9_fu_1048_p0() {
    mul_ln1118_9_fu_1048_p0 =  (sc_lv<17>) (mul_ln1118_9_fu_1048_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_9_fu_1048_p00() {
    mul_ln1118_9_fu_1048_p00 = esl_zext<26,17>(exp_res_9_V_reg_1151_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_9_fu_1048_p1() {
    mul_ln1118_9_fu_1048_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_fu_985_p0() {
    mul_ln1118_fu_985_p0 =  (sc_lv<17>) (mul_ln1118_fu_985_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_fu_985_p00() {
    mul_ln1118_fu_985_p00 = esl_zext<26,17>(exp_res_0_V_reg_1105_pp0_iter2_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_mul_ln1118_fu_985_p1() {
    mul_ln1118_fu_985_p1 =  (sc_lv<18>) (sext_ln1116_fu_851_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_or_ln340_fu_806_p2() {
    or_ln340_fu_806_p2 = (p_Result_28_fu_774_p3.read() | xor_ln340_1_fu_800_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_21_fu_570_p3() {
    p_Result_21_fu_570_p3 = p_Val2_25_fu_558_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_22_fu_596_p3() {
    p_Result_22_fu_596_p3 = p_Val2_28_fu_590_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_23_fu_632_p3() {
    p_Result_23_fu_632_p3 = p_Val2_31_fu_620_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_24_fu_672_p3() {
    p_Result_24_fu_672_p3 = p_Val2_34_fu_660_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_25_fu_698_p3() {
    p_Result_25_fu_698_p3 = p_Val2_37_fu_692_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_26_fu_720_p3() {
    p_Result_26_fu_720_p3 = p_Val2_40_fu_714_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_27_fu_761_p3() {
    p_Result_27_fu_761_p3 = ret_V_1_fu_755_p2.read().range(18, 18);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_28_fu_774_p3() {
    p_Result_28_fu_774_p3 = p_Val2_46_fu_769_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Result_s_fu_530_p3() {
    p_Result_s_fu_530_p3 = p_Val2_22_fu_518_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_22_fu_518_p2() {
    p_Val2_22_fu_518_p2 = (!zext_ln44_2_fu_510_p1.read().is_01() || !zext_ln44_3_fu_514_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln44_2_fu_510_p1.read()) + sc_biguint<18>(zext_ln44_3_fu_514_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_25_fu_558_p2() {
    p_Val2_25_fu_558_p2 = (!zext_ln44_4_fu_550_p1.read().is_01() || !zext_ln44_5_fu_554_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln44_4_fu_550_p1.read()) + sc_biguint<18>(zext_ln44_5_fu_554_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_26_fu_538_p3() {
    p_Val2_26_fu_538_p3 = (!p_Result_s_fu_530_p3.read()[0].is_01())? sc_lv<17>(): ((p_Result_s_fu_530_p3.read()[0].to_bool())? ap_const_lv17_1FFFF: add_ln746_fu_524_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_27_fu_578_p3() {
    p_Val2_27_fu_578_p3 = (!p_Result_21_fu_570_p3.read()[0].is_01())? sc_lv<17>(): ((p_Result_21_fu_570_p3.read()[0].to_bool())? ap_const_lv17_1FFFF: add_ln746_1_fu_564_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_28_fu_590_p2() {
    p_Val2_28_fu_590_p2 = (!zext_ln785_1_fu_586_p1.read().is_01() || !zext_ln785_fu_546_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln785_1_fu_586_p1.read()) + sc_biguint<18>(zext_ln785_fu_546_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_31_fu_620_p2() {
    p_Val2_31_fu_620_p2 = (!zext_ln44_6_fu_612_p1.read().is_01() || !zext_ln44_7_fu_616_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln44_6_fu_612_p1.read()) + sc_biguint<18>(zext_ln44_7_fu_616_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_34_fu_660_p2() {
    p_Val2_34_fu_660_p2 = (!zext_ln44_8_fu_652_p1.read().is_01() || !zext_ln44_9_fu_656_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln44_8_fu_652_p1.read()) + sc_biguint<18>(zext_ln44_9_fu_656_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_35_fu_640_p3() {
    p_Val2_35_fu_640_p3 = (!p_Result_23_fu_632_p3.read()[0].is_01())? sc_lv<17>(): ((p_Result_23_fu_632_p3.read()[0].to_bool())? ap_const_lv17_1FFFF: add_ln746_2_fu_626_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_36_fu_680_p3() {
    p_Val2_36_fu_680_p3 = (!p_Result_24_fu_672_p3.read()[0].is_01())? sc_lv<17>(): ((p_Result_24_fu_672_p3.read()[0].to_bool())? ap_const_lv17_1FFFF: add_ln746_3_fu_666_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_37_fu_692_p2() {
    p_Val2_37_fu_692_p2 = (!zext_ln785_3_fu_688_p1.read().is_01() || !zext_ln785_2_fu_648_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln785_3_fu_688_p1.read()) + sc_biguint<18>(zext_ln785_2_fu_648_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_38_fu_604_p3() {
    p_Val2_38_fu_604_p3 = (!p_Result_22_fu_596_p3.read()[0].is_01())? sc_lv<18>(): ((p_Result_22_fu_596_p3.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_28_fu_590_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_39_fu_706_p3() {
    p_Val2_39_fu_706_p3 = (!p_Result_25_fu_698_p3.read()[0].is_01())? sc_lv<18>(): ((p_Result_25_fu_698_p3.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_37_fu_692_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_40_fu_714_p2() {
    p_Val2_40_fu_714_p2 = (!p_Val2_39_fu_706_p3.read().is_01() || !p_Val2_38_fu_604_p3.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_Val2_39_fu_706_p3.read()) + sc_biguint<18>(p_Val2_38_fu_604_p3.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_44_fu_728_p3() {
    p_Val2_44_fu_728_p3 = (!p_Result_26_fu_720_p3.read()[0].is_01())? sc_lv<18>(): ((p_Result_26_fu_720_p3.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_40_fu_714_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_p_Val2_46_fu_769_p2() {
    p_Val2_46_fu_769_p2 = (!ret_V_fu_742_p2.read().is_01() || !p_Val2_44_reg_1157.read().is_01())? sc_lv<18>(): (sc_bigint<18>(ret_V_fu_742_p2.read()) + sc_bigint<18>(p_Val2_44_reg_1157.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_0_V() {
    res_0_V = mul_ln1118_fu_985_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_0_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_0_V_ap_vld = ap_const_logic_1;
    } else {
        res_0_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_1_V() {
    res_1_V = mul_ln1118_1_fu_992_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_1_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_1_V_ap_vld = ap_const_logic_1;
    } else {
        res_1_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_2_V() {
    res_2_V = mul_ln1118_2_fu_999_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_2_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_2_V_ap_vld = ap_const_logic_1;
    } else {
        res_2_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_3_V() {
    res_3_V = mul_ln1118_3_fu_1006_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_3_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_3_V_ap_vld = ap_const_logic_1;
    } else {
        res_3_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_4_V() {
    res_4_V = mul_ln1118_4_fu_1013_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_4_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_4_V_ap_vld = ap_const_logic_1;
    } else {
        res_4_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_5_V() {
    res_5_V = mul_ln1118_5_fu_1020_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_5_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_5_V_ap_vld = ap_const_logic_1;
    } else {
        res_5_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_6_V() {
    res_6_V = mul_ln1118_6_fu_1027_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_6_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_6_V_ap_vld = ap_const_logic_1;
    } else {
        res_6_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_7_V() {
    res_7_V = mul_ln1118_7_fu_1034_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_7_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_7_V_ap_vld = ap_const_logic_1;
    } else {
        res_7_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_8_V() {
    res_8_V = mul_ln1118_8_fu_1041_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_8_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_8_V_ap_vld = ap_const_logic_1;
    } else {
        res_8_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_9_V() {
    res_9_V = mul_ln1118_9_fu_1048_p2.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_res_9_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        res_9_V_ap_vld = ap_const_logic_1;
    } else {
        res_9_V_ap_vld = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ret_V_1_fu_755_p2() {
    ret_V_1_fu_755_p2 = (!lhs_V_fu_748_p1.read().is_01() || !rhs_V_fu_751_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(lhs_V_fu_748_p1.read()) + sc_bigint<19>(rhs_V_fu_751_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ret_V_fu_742_p2() {
    ret_V_fu_742_p2 = (!zext_ln44_1_fu_739_p1.read().is_01() || !zext_ln44_fu_736_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln44_1_fu_739_p1.read()) + sc_biguint<18>(zext_ln44_fu_736_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_rhs_V_fu_751_p1() {
    rhs_V_fu_751_p1 = esl_sext<19,18>(ret_V_fu_742_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_select_ln340_fu_822_p3() {
    select_ln340_fu_822_p3 = (!xor_ln340_fu_794_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_fu_794_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_fu_812_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_select_ln388_fu_830_p3() {
    select_ln388_fu_830_p3 = (!underflow_fu_788_p2.read()[0].is_01())? sc_lv<10>(): ((underflow_fu_788_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_fu_812_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_sext_ln1116_fu_851_p1() {
    sext_ln1116_fu_851_p1 = esl_sext<26,18>(invert_table2_q0.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_tmp_fu_812_p4() {
    tmp_fu_812_p4 = p_Val2_46_fu_769_p2.read().range(17, 8);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_underflow_fu_788_p2() {
    underflow_fu_788_p2 = (p_Result_27_fu_761_p3.read() & xor_ln786_fu_782_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_xor_ln340_1_fu_800_p2() {
    xor_ln340_1_fu_800_p2 = (p_Result_27_fu_761_p3.read() ^ ap_const_lv1_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_xor_ln340_fu_794_p2() {
    xor_ln340_fu_794_p2 = (p_Result_27_fu_761_p3.read() ^ p_Result_28_fu_774_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_xor_ln786_fu_782_p2() {
    xor_ln786_fu_782_p2 = (p_Result_28_fu_774_p3.read() ^ ap_const_lv1_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_10_fu_838_p3() {
    y_V_10_fu_838_p3 = (!or_ln340_fu_806_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_fu_806_p2.read()[0].to_bool())? select_ln340_fu_822_p3.read(): select_ln388_fu_830_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_1_fu_375_p4() {
    y_V_1_fu_375_p4 = data_1_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_2_fu_390_p4() {
    y_V_2_fu_390_p4 = data_2_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_3_fu_405_p4() {
    y_V_3_fu_405_p4 = data_3_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_4_fu_420_p4() {
    y_V_4_fu_420_p4 = data_4_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_5_fu_435_p4() {
    y_V_5_fu_435_p4 = data_5_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_6_fu_450_p4() {
    y_V_6_fu_450_p4 = data_6_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_7_fu_465_p4() {
    y_V_7_fu_465_p4 = data_7_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_8_fu_480_p4() {
    y_V_8_fu_480_p4 = data_8_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_9_fu_495_p4() {
    y_V_9_fu_495_p4 = data_9_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_y_V_fu_360_p4() {
    y_V_fu_360_p4 = data_0_V.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_1_fu_385_p1() {
    zext_ln251_1_fu_385_p1 = esl_zext<64,10>(y_V_1_fu_375_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_2_fu_400_p1() {
    zext_ln251_2_fu_400_p1 = esl_zext<64,10>(y_V_2_fu_390_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_3_fu_415_p1() {
    zext_ln251_3_fu_415_p1 = esl_zext<64,10>(y_V_3_fu_405_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_4_fu_430_p1() {
    zext_ln251_4_fu_430_p1 = esl_zext<64,10>(y_V_4_fu_420_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_5_fu_445_p1() {
    zext_ln251_5_fu_445_p1 = esl_zext<64,10>(y_V_5_fu_435_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_6_fu_460_p1() {
    zext_ln251_6_fu_460_p1 = esl_zext<64,10>(y_V_6_fu_450_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_7_fu_475_p1() {
    zext_ln251_7_fu_475_p1 = esl_zext<64,10>(y_V_7_fu_465_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_8_fu_490_p1() {
    zext_ln251_8_fu_490_p1 = esl_zext<64,10>(y_V_8_fu_480_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_9_fu_505_p1() {
    zext_ln251_9_fu_505_p1 = esl_zext<64,10>(y_V_9_fu_495_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln251_fu_370_p1() {
    zext_ln251_fu_370_p1 = esl_zext<64,10>(y_V_fu_360_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln259_fu_846_p1() {
    zext_ln259_fu_846_p1 = esl_zext<64,10>(y_V_10_fu_838_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_1_fu_739_p1() {
    zext_ln44_1_fu_739_p1 = esl_zext<18,17>(exp_res_8_V_reg_1145.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_2_fu_510_p1() {
    zext_ln44_2_fu_510_p1 = esl_zext<18,17>(exp_table1_q1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_3_fu_514_p1() {
    zext_ln44_3_fu_514_p1 = esl_zext<18,17>(exp_table1_q0.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_4_fu_550_p1() {
    zext_ln44_4_fu_550_p1 = esl_zext<18,17>(exp_table1_q3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_5_fu_554_p1() {
    zext_ln44_5_fu_554_p1 = esl_zext<18,17>(exp_table1_q2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_6_fu_612_p1() {
    zext_ln44_6_fu_612_p1 = esl_zext<18,17>(exp_table1_q5.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_7_fu_616_p1() {
    zext_ln44_7_fu_616_p1 = esl_zext<18,17>(exp_table1_q4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_8_fu_652_p1() {
    zext_ln44_8_fu_652_p1 = esl_zext<18,17>(exp_table1_q7.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_9_fu_656_p1() {
    zext_ln44_9_fu_656_p1 = esl_zext<18,17>(exp_table1_q6.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln44_fu_736_p1() {
    zext_ln44_fu_736_p1 = esl_zext<18,17>(exp_res_9_V_reg_1151.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln785_1_fu_586_p1() {
    zext_ln785_1_fu_586_p1 = esl_zext<18,17>(p_Val2_27_fu_578_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln785_2_fu_648_p1() {
    zext_ln785_2_fu_648_p1 = esl_zext<18,17>(p_Val2_35_fu_640_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln785_3_fu_688_p1() {
    zext_ln785_3_fu_688_p1 = esl_zext<18,17>(p_Val2_36_fu_680_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_zext_ln785_fu_546_p1() {
    zext_ln785_fu_546_p1 = esl_zext<18,17>(p_Val2_26_fu_538_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config10_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

