// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_ap_fixed_ap_fixed_9_6_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_0_V,
        data_1_V,
        data_2_V,
        data_3_V,
        data_4_V,
        data_5_V,
        data_6_V,
        data_7_V,
        data_8_V,
        data_9_V,
        data_10_V,
        data_11_V,
        data_12_V,
        data_13_V,
        data_14_V,
        data_15_V,
        data_16_V,
        data_17_V,
        data_18_V,
        data_19_V,
        data_20_V,
        data_21_V,
        data_22_V,
        data_23_V,
        data_24_V,
        data_25_V,
        data_26_V,
        data_27_V,
        data_28_V,
        data_29_V,
        data_30_V,
        data_31_V,
        data_32_V,
        data_33_V,
        data_34_V,
        data_35_V,
        data_36_V,
        data_37_V,
        data_38_V,
        data_39_V,
        data_40_V,
        data_41_V,
        data_42_V,
        data_43_V,
        data_44_V,
        data_45_V,
        data_46_V,
        data_47_V,
        data_48_V,
        data_49_V,
        data_50_V,
        data_51_V,
        data_52_V,
        data_53_V,
        data_54_V,
        data_55_V,
        data_56_V,
        data_57_V,
        data_58_V,
        data_59_V,
        data_60_V,
        data_61_V,
        data_62_V,
        data_63_V,
        data_64_V,
        data_65_V,
        data_66_V,
        data_67_V,
        data_68_V,
        data_69_V,
        data_70_V,
        data_71_V,
        data_72_V,
        data_73_V,
        data_74_V,
        data_75_V,
        data_76_V,
        data_77_V,
        data_78_V,
        data_79_V,
        data_80_V,
        data_81_V,
        data_82_V,
        data_83_V,
        data_84_V,
        data_85_V,
        data_86_V,
        data_87_V,
        data_88_V,
        data_89_V,
        data_90_V,
        data_91_V,
        data_92_V,
        data_93_V,
        data_94_V,
        data_95_V,
        data_96_V,
        data_97_V,
        data_98_V,
        data_99_V,
        res_0_V,
        res_0_V_ap_vld,
        res_1_V,
        res_1_V_ap_vld,
        res_2_V,
        res_2_V_ap_vld,
        res_3_V,
        res_3_V_ap_vld,
        res_4_V,
        res_4_V_ap_vld,
        res_5_V,
        res_5_V_ap_vld,
        res_6_V,
        res_6_V_ap_vld,
        res_7_V,
        res_7_V_ap_vld,
        res_8_V,
        res_8_V_ap_vld,
        res_9_V,
        res_9_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [14:0] data_0_V;
input  [14:0] data_1_V;
input  [14:0] data_2_V;
input  [14:0] data_3_V;
input  [14:0] data_4_V;
input  [14:0] data_5_V;
input  [14:0] data_6_V;
input  [14:0] data_7_V;
input  [14:0] data_8_V;
input  [14:0] data_9_V;
input  [14:0] data_10_V;
input  [14:0] data_11_V;
input  [14:0] data_12_V;
input  [14:0] data_13_V;
input  [14:0] data_14_V;
input  [14:0] data_15_V;
input  [14:0] data_16_V;
input  [14:0] data_17_V;
input  [14:0] data_18_V;
input  [14:0] data_19_V;
input  [14:0] data_20_V;
input  [14:0] data_21_V;
input  [14:0] data_22_V;
input  [14:0] data_23_V;
input  [14:0] data_24_V;
input  [14:0] data_25_V;
input  [14:0] data_26_V;
input  [14:0] data_27_V;
input  [14:0] data_28_V;
input  [14:0] data_29_V;
input  [14:0] data_30_V;
input  [14:0] data_31_V;
input  [14:0] data_32_V;
input  [14:0] data_33_V;
input  [14:0] data_34_V;
input  [14:0] data_35_V;
input  [14:0] data_36_V;
input  [14:0] data_37_V;
input  [14:0] data_38_V;
input  [14:0] data_39_V;
input  [14:0] data_40_V;
input  [14:0] data_41_V;
input  [14:0] data_42_V;
input  [14:0] data_43_V;
input  [14:0] data_44_V;
input  [14:0] data_45_V;
input  [14:0] data_46_V;
input  [14:0] data_47_V;
input  [14:0] data_48_V;
input  [14:0] data_49_V;
input  [14:0] data_50_V;
input  [14:0] data_51_V;
input  [14:0] data_52_V;
input  [14:0] data_53_V;
input  [14:0] data_54_V;
input  [14:0] data_55_V;
input  [14:0] data_56_V;
input  [14:0] data_57_V;
input  [14:0] data_58_V;
input  [14:0] data_59_V;
input  [14:0] data_60_V;
input  [14:0] data_61_V;
input  [14:0] data_62_V;
input  [14:0] data_63_V;
input  [14:0] data_64_V;
input  [14:0] data_65_V;
input  [14:0] data_66_V;
input  [14:0] data_67_V;
input  [14:0] data_68_V;
input  [14:0] data_69_V;
input  [14:0] data_70_V;
input  [14:0] data_71_V;
input  [14:0] data_72_V;
input  [14:0] data_73_V;
input  [14:0] data_74_V;
input  [14:0] data_75_V;
input  [14:0] data_76_V;
input  [14:0] data_77_V;
input  [14:0] data_78_V;
input  [14:0] data_79_V;
input  [14:0] data_80_V;
input  [14:0] data_81_V;
input  [14:0] data_82_V;
input  [14:0] data_83_V;
input  [14:0] data_84_V;
input  [14:0] data_85_V;
input  [14:0] data_86_V;
input  [14:0] data_87_V;
input  [14:0] data_88_V;
input  [14:0] data_89_V;
input  [14:0] data_90_V;
input  [14:0] data_91_V;
input  [14:0] data_92_V;
input  [14:0] data_93_V;
input  [14:0] data_94_V;
input  [14:0] data_95_V;
input  [14:0] data_96_V;
input  [14:0] data_97_V;
input  [14:0] data_98_V;
input  [14:0] data_99_V;
output  [8:0] res_0_V;
output   res_0_V_ap_vld;
output  [8:0] res_1_V;
output   res_1_V_ap_vld;
output  [8:0] res_2_V;
output   res_2_V_ap_vld;
output  [8:0] res_3_V;
output   res_3_V_ap_vld;
output  [8:0] res_4_V;
output   res_4_V_ap_vld;
output  [8:0] res_5_V;
output   res_5_V_ap_vld;
output  [8:0] res_6_V;
output   res_6_V_ap_vld;
output  [8:0] res_7_V;
output   res_7_V_ap_vld;
output  [8:0] res_8_V;
output   res_8_V_ap_vld;
output  [8:0] res_9_V;
output   res_9_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg res_0_V_ap_vld;
reg res_1_V_ap_vld;
reg res_2_V_ap_vld;
reg res_3_V_ap_vld;
reg res_4_V_ap_vld;
reg res_5_V_ap_vld;
reg res_6_V_ap_vld;
reg res_7_V_ap_vld;
reg res_8_V_ap_vld;
reg res_9_V_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln151_fu_2699_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] outidx_address0;
reg    outidx_ce0;
wire   [3:0] outidx_q0;
wire   [9:0] w8_V_address0;
reg    w8_V_ce0;
wire  signed [10:0] w8_V_q0;
reg   [9:0] w_index48_reg_1014;
reg   [31:0] in_index_0_i47_reg_1028;
reg   [15:0] p_Val2_46_reg_1057;
reg   [15:0] p_Val2_3244_reg_1071;
reg   [15:0] p_Val2_3342_reg_1085;
reg   [15:0] p_Val2_3440_reg_1099;
reg   [15:0] p_Val2_3538_reg_1113;
reg   [15:0] p_Val2_3636_reg_1127;
reg   [15:0] p_Val2_3734_reg_1141;
reg   [15:0] p_Val2_3832_reg_1155;
reg   [15:0] p_Val2_3930_reg_1169;
reg   [15:0] p_Val2_4028_reg_1183;
reg   [15:0] acc_0_V_026_reg_1197;
reg   [15:0] acc_1_V_025_reg_1211;
reg   [15:0] acc_2_V_024_reg_1225;
reg   [15:0] acc_3_V_023_reg_1239;
reg   [15:0] acc_4_V_022_reg_1253;
reg   [15:0] acc_5_V_021_reg_1267;
reg   [15:0] acc_6_V_020_reg_1281;
reg   [15:0] acc_7_V_019_reg_1295;
reg   [15:0] acc_8_V_018_reg_1309;
reg   [15:0] acc_9_V_017_reg_1323;
wire   [15:0] tmp_4_fu_2467_p102;
reg  signed [15:0] tmp_4_reg_2895;
wire   [9:0] w_index_fu_2673_p2;
reg   [9:0] w_index_reg_2905;
wire   [31:0] select_ln168_fu_2691_p3;
reg   [31:0] select_ln168_reg_2910;
reg   [0:0] icmp_ln151_reg_2915;
reg   [0:0] icmp_ln151_reg_2915_pp0_iter1_reg;
reg   [3:0] out_index_reg_2919;
reg   [15:0] trunc_ln1_reg_2924;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [9:0] ap_phi_mux_w_index48_phi_fu_1018_p6;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_in_index_0_i47_phi_fu_1032_p6;
reg   [15:0] ap_phi_mux_p_Val2_48_phi_fu_2025_p20;
reg   [15:0] ap_phi_mux_p_Val2_49_phi_fu_1989_p20;
reg   [15:0] ap_phi_mux_p_Val2_50_phi_fu_1953_p20;
reg   [15:0] ap_phi_mux_p_Val2_51_phi_fu_1917_p20;
reg   [15:0] ap_phi_mux_p_Val2_52_phi_fu_1881_p20;
reg   [15:0] ap_phi_mux_p_Val2_53_phi_fu_1845_p20;
reg   [15:0] ap_phi_mux_p_Val2_54_phi_fu_1809_p20;
reg   [15:0] ap_phi_mux_p_Val2_55_phi_fu_1773_p20;
reg   [15:0] ap_phi_mux_p_Val2_56_phi_fu_1737_p20;
reg   [15:0] ap_phi_mux_p_Val2_57_phi_fu_1701_p20;
reg   [15:0] ap_phi_mux_acc_0_V_1_phi_fu_1665_p20;
reg   [15:0] ap_phi_mux_acc_1_V_1_phi_fu_1629_p20;
reg   [15:0] ap_phi_mux_acc_2_V_1_phi_fu_1593_p20;
reg   [15:0] ap_phi_mux_acc_3_V_1_phi_fu_1557_p20;
reg   [15:0] ap_phi_mux_acc_4_V_1_phi_fu_1521_p20;
reg   [15:0] ap_phi_mux_acc_5_V_1_phi_fu_1485_p20;
reg   [15:0] ap_phi_mux_acc_6_V_1_phi_fu_1449_p20;
reg   [15:0] ap_phi_mux_acc_7_V_1_phi_fu_1413_p20;
reg   [15:0] ap_phi_mux_acc_8_V_1_phi_fu_1377_p20;
reg   [15:0] ap_phi_mux_acc_9_V_1_phi_fu_1341_p20;
wire   [15:0] acc_0_V_fu_2746_p2;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_9_V_1_reg_1337;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_8_V_1_reg_1373;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_7_V_1_reg_1409;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_6_V_1_reg_1445;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_5_V_1_reg_1481;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_4_V_1_reg_1517;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_3_V_1_reg_1553;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_2_V_1_reg_1589;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_1_V_1_reg_1625;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_0_V_1_reg_1661;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_57_reg_1697;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_56_reg_1733;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_55_reg_1769;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_54_reg_1805;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_53_reg_1841;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_52_reg_1877;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_51_reg_1913;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_50_reg_1949;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_49_reg_1985;
wire   [15:0] ap_phi_reg_pp0_iter2_p_Val2_48_reg_2021;
wire   [63:0] zext_ln155_fu_2057_p1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] tmp_4_fu_2467_p1;
wire   [15:0] tmp_4_fu_2467_p2;
wire   [15:0] tmp_4_fu_2467_p3;
wire   [15:0] tmp_4_fu_2467_p4;
wire   [15:0] tmp_4_fu_2467_p5;
wire   [15:0] tmp_4_fu_2467_p6;
wire   [15:0] tmp_4_fu_2467_p7;
wire   [15:0] tmp_4_fu_2467_p8;
wire   [15:0] tmp_4_fu_2467_p9;
wire   [15:0] tmp_4_fu_2467_p10;
wire   [15:0] tmp_4_fu_2467_p11;
wire   [15:0] tmp_4_fu_2467_p12;
wire   [15:0] tmp_4_fu_2467_p13;
wire   [15:0] tmp_4_fu_2467_p14;
wire   [15:0] tmp_4_fu_2467_p15;
wire   [15:0] tmp_4_fu_2467_p16;
wire   [15:0] tmp_4_fu_2467_p17;
wire   [15:0] tmp_4_fu_2467_p18;
wire   [15:0] tmp_4_fu_2467_p19;
wire   [15:0] tmp_4_fu_2467_p20;
wire   [15:0] tmp_4_fu_2467_p21;
wire   [15:0] tmp_4_fu_2467_p22;
wire   [15:0] tmp_4_fu_2467_p23;
wire   [15:0] tmp_4_fu_2467_p24;
wire   [15:0] tmp_4_fu_2467_p25;
wire   [15:0] tmp_4_fu_2467_p26;
wire   [15:0] tmp_4_fu_2467_p27;
wire   [15:0] tmp_4_fu_2467_p28;
wire   [15:0] tmp_4_fu_2467_p29;
wire   [15:0] tmp_4_fu_2467_p30;
wire   [15:0] tmp_4_fu_2467_p31;
wire   [15:0] tmp_4_fu_2467_p32;
wire   [15:0] tmp_4_fu_2467_p33;
wire   [15:0] tmp_4_fu_2467_p34;
wire   [15:0] tmp_4_fu_2467_p35;
wire   [15:0] tmp_4_fu_2467_p36;
wire   [15:0] tmp_4_fu_2467_p37;
wire   [15:0] tmp_4_fu_2467_p38;
wire   [15:0] tmp_4_fu_2467_p39;
wire   [15:0] tmp_4_fu_2467_p40;
wire   [15:0] tmp_4_fu_2467_p41;
wire   [15:0] tmp_4_fu_2467_p42;
wire   [15:0] tmp_4_fu_2467_p43;
wire   [15:0] tmp_4_fu_2467_p44;
wire   [15:0] tmp_4_fu_2467_p45;
wire   [15:0] tmp_4_fu_2467_p46;
wire   [15:0] tmp_4_fu_2467_p47;
wire   [15:0] tmp_4_fu_2467_p48;
wire   [15:0] tmp_4_fu_2467_p49;
wire   [15:0] tmp_4_fu_2467_p50;
wire   [15:0] tmp_4_fu_2467_p51;
wire   [15:0] tmp_4_fu_2467_p52;
wire   [15:0] tmp_4_fu_2467_p53;
wire   [15:0] tmp_4_fu_2467_p54;
wire   [15:0] tmp_4_fu_2467_p55;
wire   [15:0] tmp_4_fu_2467_p56;
wire   [15:0] tmp_4_fu_2467_p57;
wire   [15:0] tmp_4_fu_2467_p58;
wire   [15:0] tmp_4_fu_2467_p59;
wire   [15:0] tmp_4_fu_2467_p60;
wire   [15:0] tmp_4_fu_2467_p61;
wire   [15:0] tmp_4_fu_2467_p62;
wire   [15:0] tmp_4_fu_2467_p63;
wire   [15:0] tmp_4_fu_2467_p64;
wire   [15:0] tmp_4_fu_2467_p65;
wire   [15:0] tmp_4_fu_2467_p66;
wire   [15:0] tmp_4_fu_2467_p67;
wire   [15:0] tmp_4_fu_2467_p68;
wire   [15:0] tmp_4_fu_2467_p69;
wire   [15:0] tmp_4_fu_2467_p70;
wire   [15:0] tmp_4_fu_2467_p71;
wire   [15:0] tmp_4_fu_2467_p72;
wire   [15:0] tmp_4_fu_2467_p73;
wire   [15:0] tmp_4_fu_2467_p74;
wire   [15:0] tmp_4_fu_2467_p75;
wire   [15:0] tmp_4_fu_2467_p76;
wire   [15:0] tmp_4_fu_2467_p77;
wire   [15:0] tmp_4_fu_2467_p78;
wire   [15:0] tmp_4_fu_2467_p79;
wire   [15:0] tmp_4_fu_2467_p80;
wire   [15:0] tmp_4_fu_2467_p81;
wire   [15:0] tmp_4_fu_2467_p82;
wire   [15:0] tmp_4_fu_2467_p83;
wire   [15:0] tmp_4_fu_2467_p84;
wire   [15:0] tmp_4_fu_2467_p85;
wire   [15:0] tmp_4_fu_2467_p86;
wire   [15:0] tmp_4_fu_2467_p87;
wire   [15:0] tmp_4_fu_2467_p88;
wire   [15:0] tmp_4_fu_2467_p89;
wire   [15:0] tmp_4_fu_2467_p90;
wire   [15:0] tmp_4_fu_2467_p91;
wire   [15:0] tmp_4_fu_2467_p92;
wire   [15:0] tmp_4_fu_2467_p93;
wire   [15:0] tmp_4_fu_2467_p94;
wire   [15:0] tmp_4_fu_2467_p95;
wire   [15:0] tmp_4_fu_2467_p96;
wire   [15:0] tmp_4_fu_2467_p97;
wire   [15:0] tmp_4_fu_2467_p98;
wire   [15:0] tmp_4_fu_2467_p99;
wire   [15:0] tmp_4_fu_2467_p100;
wire   [6:0] tmp_4_fu_2467_p101;
wire   [31:0] in_index_fu_2679_p2;
wire   [0:0] icmp_ln168_fu_2685_p2;
wire  signed [25:0] r_V_fu_2883_p2;
wire   [15:0] tmp_5_fu_2721_p12;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_303;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

dense_resource_ap_fixed_ap_fixed_9_6_5_3_0_config8_s_outidx #(
    .DataWidth( 4 ),
    .AddressRange( 1000 ),
    .AddressWidth( 10 ))
outidx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_address0),
    .ce0(outidx_ce0),
    .q0(outidx_q0)
);

dense_resource_ap_fixed_ap_fixed_9_6_5_3_0_config8_s_w8_V #(
    .DataWidth( 11 ),
    .AddressRange( 1000 ),
    .AddressWidth( 10 ))
w8_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w8_V_address0),
    .ce0(w8_V_ce0),
    .q0(w8_V_q0)
);

myproject_mux_1007_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 16 ),
    .din40_WIDTH( 16 ),
    .din41_WIDTH( 16 ),
    .din42_WIDTH( 16 ),
    .din43_WIDTH( 16 ),
    .din44_WIDTH( 16 ),
    .din45_WIDTH( 16 ),
    .din46_WIDTH( 16 ),
    .din47_WIDTH( 16 ),
    .din48_WIDTH( 16 ),
    .din49_WIDTH( 16 ),
    .din50_WIDTH( 16 ),
    .din51_WIDTH( 16 ),
    .din52_WIDTH( 16 ),
    .din53_WIDTH( 16 ),
    .din54_WIDTH( 16 ),
    .din55_WIDTH( 16 ),
    .din56_WIDTH( 16 ),
    .din57_WIDTH( 16 ),
    .din58_WIDTH( 16 ),
    .din59_WIDTH( 16 ),
    .din60_WIDTH( 16 ),
    .din61_WIDTH( 16 ),
    .din62_WIDTH( 16 ),
    .din63_WIDTH( 16 ),
    .din64_WIDTH( 16 ),
    .din65_WIDTH( 16 ),
    .din66_WIDTH( 16 ),
    .din67_WIDTH( 16 ),
    .din68_WIDTH( 16 ),
    .din69_WIDTH( 16 ),
    .din70_WIDTH( 16 ),
    .din71_WIDTH( 16 ),
    .din72_WIDTH( 16 ),
    .din73_WIDTH( 16 ),
    .din74_WIDTH( 16 ),
    .din75_WIDTH( 16 ),
    .din76_WIDTH( 16 ),
    .din77_WIDTH( 16 ),
    .din78_WIDTH( 16 ),
    .din79_WIDTH( 16 ),
    .din80_WIDTH( 16 ),
    .din81_WIDTH( 16 ),
    .din82_WIDTH( 16 ),
    .din83_WIDTH( 16 ),
    .din84_WIDTH( 16 ),
    .din85_WIDTH( 16 ),
    .din86_WIDTH( 16 ),
    .din87_WIDTH( 16 ),
    .din88_WIDTH( 16 ),
    .din89_WIDTH( 16 ),
    .din90_WIDTH( 16 ),
    .din91_WIDTH( 16 ),
    .din92_WIDTH( 16 ),
    .din93_WIDTH( 16 ),
    .din94_WIDTH( 16 ),
    .din95_WIDTH( 16 ),
    .din96_WIDTH( 16 ),
    .din97_WIDTH( 16 ),
    .din98_WIDTH( 16 ),
    .din99_WIDTH( 16 ),
    .din100_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
myproject_mux_1007_16_1_1_U725(
    .din0(tmp_4_fu_2467_p1),
    .din1(tmp_4_fu_2467_p2),
    .din2(tmp_4_fu_2467_p3),
    .din3(tmp_4_fu_2467_p4),
    .din4(tmp_4_fu_2467_p5),
    .din5(tmp_4_fu_2467_p6),
    .din6(tmp_4_fu_2467_p7),
    .din7(tmp_4_fu_2467_p8),
    .din8(tmp_4_fu_2467_p9),
    .din9(tmp_4_fu_2467_p10),
    .din10(tmp_4_fu_2467_p11),
    .din11(tmp_4_fu_2467_p12),
    .din12(tmp_4_fu_2467_p13),
    .din13(tmp_4_fu_2467_p14),
    .din14(tmp_4_fu_2467_p15),
    .din15(tmp_4_fu_2467_p16),
    .din16(tmp_4_fu_2467_p17),
    .din17(tmp_4_fu_2467_p18),
    .din18(tmp_4_fu_2467_p19),
    .din19(tmp_4_fu_2467_p20),
    .din20(tmp_4_fu_2467_p21),
    .din21(tmp_4_fu_2467_p22),
    .din22(tmp_4_fu_2467_p23),
    .din23(tmp_4_fu_2467_p24),
    .din24(tmp_4_fu_2467_p25),
    .din25(tmp_4_fu_2467_p26),
    .din26(tmp_4_fu_2467_p27),
    .din27(tmp_4_fu_2467_p28),
    .din28(tmp_4_fu_2467_p29),
    .din29(tmp_4_fu_2467_p30),
    .din30(tmp_4_fu_2467_p31),
    .din31(tmp_4_fu_2467_p32),
    .din32(tmp_4_fu_2467_p33),
    .din33(tmp_4_fu_2467_p34),
    .din34(tmp_4_fu_2467_p35),
    .din35(tmp_4_fu_2467_p36),
    .din36(tmp_4_fu_2467_p37),
    .din37(tmp_4_fu_2467_p38),
    .din38(tmp_4_fu_2467_p39),
    .din39(tmp_4_fu_2467_p40),
    .din40(tmp_4_fu_2467_p41),
    .din41(tmp_4_fu_2467_p42),
    .din42(tmp_4_fu_2467_p43),
    .din43(tmp_4_fu_2467_p44),
    .din44(tmp_4_fu_2467_p45),
    .din45(tmp_4_fu_2467_p46),
    .din46(tmp_4_fu_2467_p47),
    .din47(tmp_4_fu_2467_p48),
    .din48(tmp_4_fu_2467_p49),
    .din49(tmp_4_fu_2467_p50),
    .din50(tmp_4_fu_2467_p51),
    .din51(tmp_4_fu_2467_p52),
    .din52(tmp_4_fu_2467_p53),
    .din53(tmp_4_fu_2467_p54),
    .din54(tmp_4_fu_2467_p55),
    .din55(tmp_4_fu_2467_p56),
    .din56(tmp_4_fu_2467_p57),
    .din57(tmp_4_fu_2467_p58),
    .din58(tmp_4_fu_2467_p59),
    .din59(tmp_4_fu_2467_p60),
    .din60(tmp_4_fu_2467_p61),
    .din61(tmp_4_fu_2467_p62),
    .din62(tmp_4_fu_2467_p63),
    .din63(tmp_4_fu_2467_p64),
    .din64(tmp_4_fu_2467_p65),
    .din65(tmp_4_fu_2467_p66),
    .din66(tmp_4_fu_2467_p67),
    .din67(tmp_4_fu_2467_p68),
    .din68(tmp_4_fu_2467_p69),
    .din69(tmp_4_fu_2467_p70),
    .din70(tmp_4_fu_2467_p71),
    .din71(tmp_4_fu_2467_p72),
    .din72(tmp_4_fu_2467_p73),
    .din73(tmp_4_fu_2467_p74),
    .din74(tmp_4_fu_2467_p75),
    .din75(tmp_4_fu_2467_p76),
    .din76(tmp_4_fu_2467_p77),
    .din77(tmp_4_fu_2467_p78),
    .din78(tmp_4_fu_2467_p79),
    .din79(tmp_4_fu_2467_p80),
    .din80(tmp_4_fu_2467_p81),
    .din81(tmp_4_fu_2467_p82),
    .din82(tmp_4_fu_2467_p83),
    .din83(tmp_4_fu_2467_p84),
    .din84(tmp_4_fu_2467_p85),
    .din85(tmp_4_fu_2467_p86),
    .din86(tmp_4_fu_2467_p87),
    .din87(tmp_4_fu_2467_p88),
    .din88(tmp_4_fu_2467_p89),
    .din89(tmp_4_fu_2467_p90),
    .din90(tmp_4_fu_2467_p91),
    .din91(tmp_4_fu_2467_p92),
    .din92(tmp_4_fu_2467_p93),
    .din93(tmp_4_fu_2467_p94),
    .din94(tmp_4_fu_2467_p95),
    .din95(tmp_4_fu_2467_p96),
    .din96(tmp_4_fu_2467_p97),
    .din97(tmp_4_fu_2467_p98),
    .din98(tmp_4_fu_2467_p99),
    .din99(tmp_4_fu_2467_p100),
    .din100(tmp_4_fu_2467_p101),
    .dout(tmp_4_fu_2467_p102)
);

myproject_mux_104_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
myproject_mux_104_16_1_1_U726(
    .din0(acc_0_V_026_reg_1197),
    .din1(acc_1_V_025_reg_1211),
    .din2(acc_2_V_024_reg_1225),
    .din3(acc_3_V_023_reg_1239),
    .din4(acc_4_V_022_reg_1253),
    .din5(acc_5_V_021_reg_1267),
    .din6(acc_6_V_020_reg_1281),
    .din7(acc_7_V_019_reg_1295),
    .din8(acc_8_V_018_reg_1309),
    .din9(acc_9_V_017_reg_1323),
    .din10(out_index_reg_2919),
    .dout(tmp_5_fu_2721_p12)
);

myproject_mul_mul_11s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_11s_16s_26_1_1_U727(
    .din0(w8_V_q0),
    .din1(tmp_4_reg_2895),
    .dout(r_V_fu_2883_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_0_V_026_reg_1197 <= ap_phi_mux_acc_0_V_1_phi_fu_1665_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_0_V_026_reg_1197 <= 16'd65480;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_1_V_025_reg_1211 <= ap_phi_mux_acc_1_V_1_phi_fu_1629_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_1_V_025_reg_1211 <= 16'd65418;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_2_V_024_reg_1225 <= ap_phi_mux_acc_2_V_1_phi_fu_1593_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_2_V_024_reg_1225 <= 16'd54;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_3_V_023_reg_1239 <= ap_phi_mux_acc_3_V_1_phi_fu_1557_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_3_V_023_reg_1239 <= 16'd12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_4_V_022_reg_1253 <= ap_phi_mux_acc_4_V_1_phi_fu_1521_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_4_V_022_reg_1253 <= 16'd48;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_5_V_021_reg_1267 <= ap_phi_mux_acc_5_V_1_phi_fu_1485_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_5_V_021_reg_1267 <= 16'd65420;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_6_V_020_reg_1281 <= ap_phi_mux_acc_6_V_1_phi_fu_1449_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_6_V_020_reg_1281 <= 16'd58;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_7_V_019_reg_1295 <= ap_phi_mux_acc_7_V_1_phi_fu_1413_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_7_V_019_reg_1295 <= 16'd65500;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_8_V_018_reg_1309 <= ap_phi_mux_acc_8_V_1_phi_fu_1377_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_8_V_018_reg_1309 <= 16'd28;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_9_V_017_reg_1323 <= ap_phi_mux_acc_9_V_1_phi_fu_1341_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_9_V_017_reg_1323 <= 16'd65524;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        in_index_0_i47_reg_1028 <= select_ln168_reg_2910;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index_0_i47_reg_1028 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_3244_reg_1071 <= ap_phi_mux_p_Val2_49_phi_fu_1989_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_3244_reg_1071 <= 16'd65418;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_3342_reg_1085 <= ap_phi_mux_p_Val2_50_phi_fu_1953_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_3342_reg_1085 <= 16'd54;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_3440_reg_1099 <= ap_phi_mux_p_Val2_51_phi_fu_1917_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_3440_reg_1099 <= 16'd12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_3538_reg_1113 <= ap_phi_mux_p_Val2_52_phi_fu_1881_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_3538_reg_1113 <= 16'd48;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_3636_reg_1127 <= ap_phi_mux_p_Val2_53_phi_fu_1845_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_3636_reg_1127 <= 16'd65420;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_3734_reg_1141 <= ap_phi_mux_p_Val2_54_phi_fu_1809_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_3734_reg_1141 <= 16'd58;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_3832_reg_1155 <= ap_phi_mux_p_Val2_55_phi_fu_1773_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_3832_reg_1155 <= 16'd65500;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_3930_reg_1169 <= ap_phi_mux_p_Val2_56_phi_fu_1737_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_3930_reg_1169 <= 16'd28;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_4028_reg_1183 <= ap_phi_mux_p_Val2_57_phi_fu_1701_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_4028_reg_1183 <= 16'd65524;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_46_reg_1057 <= ap_phi_mux_p_Val2_48_phi_fu_2025_p20;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_46_reg_1057 <= 16'd65480;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        w_index48_reg_1014 <= w_index_reg_2905;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index48_reg_1014 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln151_reg_2915 <= icmp_ln151_fu_2699_p2;
        icmp_ln151_reg_2915_pp0_iter1_reg <= icmp_ln151_reg_2915;
        out_index_reg_2919 <= outidx_q0;
        tmp_4_reg_2895 <= tmp_4_fu_2467_p102;
        trunc_ln1_reg_2924 <= {{r_V_fu_2883_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln168_reg_2910 <= select_ln168_fu_2691_p3;
        w_index_reg_2905 <= w_index_fu_2673_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd0)) begin
        ap_phi_mux_acc_0_V_1_phi_fu_1665_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_0_V_1_phi_fu_1665_p20 = acc_0_V_026_reg_1197;
    end else begin
        ap_phi_mux_acc_0_V_1_phi_fu_1665_p20 = ap_phi_reg_pp0_iter2_acc_0_V_1_reg_1661;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd1)) begin
        ap_phi_mux_acc_1_V_1_phi_fu_1629_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_1_V_1_phi_fu_1629_p20 = acc_1_V_025_reg_1211;
    end else begin
        ap_phi_mux_acc_1_V_1_phi_fu_1629_p20 = ap_phi_reg_pp0_iter2_acc_1_V_1_reg_1625;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd2)) begin
        ap_phi_mux_acc_2_V_1_phi_fu_1593_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_2_V_1_phi_fu_1593_p20 = acc_2_V_024_reg_1225;
    end else begin
        ap_phi_mux_acc_2_V_1_phi_fu_1593_p20 = ap_phi_reg_pp0_iter2_acc_2_V_1_reg_1589;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd3)) begin
        ap_phi_mux_acc_3_V_1_phi_fu_1557_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_3_V_1_phi_fu_1557_p20 = acc_3_V_023_reg_1239;
    end else begin
        ap_phi_mux_acc_3_V_1_phi_fu_1557_p20 = ap_phi_reg_pp0_iter2_acc_3_V_1_reg_1553;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd4)) begin
        ap_phi_mux_acc_4_V_1_phi_fu_1521_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_4_V_1_phi_fu_1521_p20 = acc_4_V_022_reg_1253;
    end else begin
        ap_phi_mux_acc_4_V_1_phi_fu_1521_p20 = ap_phi_reg_pp0_iter2_acc_4_V_1_reg_1517;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd5)) begin
        ap_phi_mux_acc_5_V_1_phi_fu_1485_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_5_V_1_phi_fu_1485_p20 = acc_5_V_021_reg_1267;
    end else begin
        ap_phi_mux_acc_5_V_1_phi_fu_1485_p20 = ap_phi_reg_pp0_iter2_acc_5_V_1_reg_1481;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd6)) begin
        ap_phi_mux_acc_6_V_1_phi_fu_1449_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_6_V_1_phi_fu_1449_p20 = acc_6_V_020_reg_1281;
    end else begin
        ap_phi_mux_acc_6_V_1_phi_fu_1449_p20 = ap_phi_reg_pp0_iter2_acc_6_V_1_reg_1445;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd7)) begin
        ap_phi_mux_acc_7_V_1_phi_fu_1413_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_7_V_1_phi_fu_1413_p20 = acc_7_V_019_reg_1295;
    end else begin
        ap_phi_mux_acc_7_V_1_phi_fu_1413_p20 = ap_phi_reg_pp0_iter2_acc_7_V_1_reg_1409;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd8)) begin
        ap_phi_mux_acc_8_V_1_phi_fu_1377_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_acc_8_V_1_phi_fu_1377_p20 = acc_8_V_018_reg_1309;
    end else begin
        ap_phi_mux_acc_8_V_1_phi_fu_1377_p20 = ap_phi_reg_pp0_iter2_acc_8_V_1_reg_1373;
    end
end

always @ (*) begin
    if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8))) begin
        ap_phi_mux_acc_9_V_1_phi_fu_1341_p20 = acc_9_V_017_reg_1323;
    end else if (((out_index_reg_2919 == 4'd9) | ((out_index_reg_2919 == 4'd10) | ((out_index_reg_2919 == 4'd11) | ((out_index_reg_2919 == 4'd12) | ((out_index_reg_2919 == 4'd13) | ((out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15)))))))) begin
        ap_phi_mux_acc_9_V_1_phi_fu_1341_p20 = acc_0_V_fu_2746_p2;
    end else begin
        ap_phi_mux_acc_9_V_1_phi_fu_1341_p20 = ap_phi_reg_pp0_iter2_acc_9_V_1_reg_1337;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_303)) begin
        if ((icmp_ln151_reg_2915 == 1'd1)) begin
            ap_phi_mux_in_index_0_i47_phi_fu_1032_p6 = 32'd0;
        end else if ((icmp_ln151_reg_2915 == 1'd0)) begin
            ap_phi_mux_in_index_0_i47_phi_fu_1032_p6 = select_ln168_reg_2910;
        end else begin
            ap_phi_mux_in_index_0_i47_phi_fu_1032_p6 = in_index_0_i47_reg_1028;
        end
    end else begin
        ap_phi_mux_in_index_0_i47_phi_fu_1032_p6 = in_index_0_i47_reg_1028;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd0)) begin
        ap_phi_mux_p_Val2_48_phi_fu_2025_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_48_phi_fu_2025_p20 = p_Val2_46_reg_1057;
    end else begin
        ap_phi_mux_p_Val2_48_phi_fu_2025_p20 = ap_phi_reg_pp0_iter2_p_Val2_48_reg_2021;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd1)) begin
        ap_phi_mux_p_Val2_49_phi_fu_1989_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_49_phi_fu_1989_p20 = p_Val2_3244_reg_1071;
    end else begin
        ap_phi_mux_p_Val2_49_phi_fu_1989_p20 = ap_phi_reg_pp0_iter2_p_Val2_49_reg_1985;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd2)) begin
        ap_phi_mux_p_Val2_50_phi_fu_1953_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_50_phi_fu_1953_p20 = p_Val2_3342_reg_1085;
    end else begin
        ap_phi_mux_p_Val2_50_phi_fu_1953_p20 = ap_phi_reg_pp0_iter2_p_Val2_50_reg_1949;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd3)) begin
        ap_phi_mux_p_Val2_51_phi_fu_1917_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_51_phi_fu_1917_p20 = p_Val2_3440_reg_1099;
    end else begin
        ap_phi_mux_p_Val2_51_phi_fu_1917_p20 = ap_phi_reg_pp0_iter2_p_Val2_51_reg_1913;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd4)) begin
        ap_phi_mux_p_Val2_52_phi_fu_1881_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_52_phi_fu_1881_p20 = p_Val2_3538_reg_1113;
    end else begin
        ap_phi_mux_p_Val2_52_phi_fu_1881_p20 = ap_phi_reg_pp0_iter2_p_Val2_52_reg_1877;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd5)) begin
        ap_phi_mux_p_Val2_53_phi_fu_1845_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_53_phi_fu_1845_p20 = p_Val2_3636_reg_1127;
    end else begin
        ap_phi_mux_p_Val2_53_phi_fu_1845_p20 = ap_phi_reg_pp0_iter2_p_Val2_53_reg_1841;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd6)) begin
        ap_phi_mux_p_Val2_54_phi_fu_1809_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_54_phi_fu_1809_p20 = p_Val2_3734_reg_1141;
    end else begin
        ap_phi_mux_p_Val2_54_phi_fu_1809_p20 = ap_phi_reg_pp0_iter2_p_Val2_54_reg_1805;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd7)) begin
        ap_phi_mux_p_Val2_55_phi_fu_1773_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd8) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_55_phi_fu_1773_p20 = p_Val2_3832_reg_1155;
    end else begin
        ap_phi_mux_p_Val2_55_phi_fu_1773_p20 = ap_phi_reg_pp0_iter2_p_Val2_55_reg_1769;
    end
end

always @ (*) begin
    if ((out_index_reg_2919 == 4'd8)) begin
        ap_phi_mux_p_Val2_56_phi_fu_1737_p20 = acc_0_V_fu_2746_p2;
    end else if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd9) | (out_index_reg_2919 == 4'd10) | (out_index_reg_2919 == 4'd11) | (out_index_reg_2919 == 4'd12) | (out_index_reg_2919 == 4'd13) | (out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15))) begin
        ap_phi_mux_p_Val2_56_phi_fu_1737_p20 = p_Val2_3930_reg_1169;
    end else begin
        ap_phi_mux_p_Val2_56_phi_fu_1737_p20 = ap_phi_reg_pp0_iter2_p_Val2_56_reg_1733;
    end
end

always @ (*) begin
    if (((out_index_reg_2919 == 4'd0) | (out_index_reg_2919 == 4'd1) | (out_index_reg_2919 == 4'd2) | (out_index_reg_2919 == 4'd3) | (out_index_reg_2919 == 4'd4) | (out_index_reg_2919 == 4'd5) | (out_index_reg_2919 == 4'd6) | (out_index_reg_2919 == 4'd7) | (out_index_reg_2919 == 4'd8))) begin
        ap_phi_mux_p_Val2_57_phi_fu_1701_p20 = p_Val2_4028_reg_1183;
    end else if (((out_index_reg_2919 == 4'd9) | ((out_index_reg_2919 == 4'd10) | ((out_index_reg_2919 == 4'd11) | ((out_index_reg_2919 == 4'd12) | ((out_index_reg_2919 == 4'd13) | ((out_index_reg_2919 == 4'd14) | (out_index_reg_2919 == 4'd15)))))))) begin
        ap_phi_mux_p_Val2_57_phi_fu_1701_p20 = acc_0_V_fu_2746_p2;
    end else begin
        ap_phi_mux_p_Val2_57_phi_fu_1701_p20 = ap_phi_reg_pp0_iter2_p_Val2_57_reg_1697;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_303)) begin
        if ((icmp_ln151_reg_2915 == 1'd1)) begin
            ap_phi_mux_w_index48_phi_fu_1018_p6 = 10'd0;
        end else if ((icmp_ln151_reg_2915 == 1'd0)) begin
            ap_phi_mux_w_index48_phi_fu_1018_p6 = w_index_reg_2905;
        end else begin
            ap_phi_mux_w_index48_phi_fu_1018_p6 = w_index48_reg_1014;
        end
    end else begin
        ap_phi_mux_w_index48_phi_fu_1018_p6 = w_index48_reg_1014;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_fu_2699_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_ce0 = 1'b1;
    end else begin
        outidx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_0_V_ap_vld = 1'b1;
    end else begin
        res_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_1_V_ap_vld = 1'b1;
    end else begin
        res_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_2_V_ap_vld = 1'b1;
    end else begin
        res_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_3_V_ap_vld = 1'b1;
    end else begin
        res_3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_4_V_ap_vld = 1'b1;
    end else begin
        res_4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_5_V_ap_vld = 1'b1;
    end else begin
        res_5_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_6_V_ap_vld = 1'b1;
    end else begin
        res_6_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_7_V_ap_vld = 1'b1;
    end else begin
        res_7_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_8_V_ap_vld = 1'b1;
    end else begin
        res_8_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2915_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_9_V_ap_vld = 1'b1;
    end else begin
        res_9_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w8_V_ce0 = 1'b1;
    end else begin
        w8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_2746_p2 = (tmp_5_fu_2721_p12 + trunc_ln1_reg_2924);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_303 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter2_acc_0_V_1_reg_1661 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_1_V_1_reg_1625 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_2_V_1_reg_1589 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_3_V_1_reg_1553 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_4_V_1_reg_1517 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_5_V_1_reg_1481 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_6_V_1_reg_1445 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_7_V_1_reg_1409 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_8_V_1_reg_1373 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_9_V_1_reg_1337 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_48_reg_2021 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_49_reg_1985 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_50_reg_1949 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_51_reg_1913 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_52_reg_1877 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_53_reg_1841 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_54_reg_1805 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_55_reg_1769 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_56_reg_1733 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_57_reg_1697 = 'bx;

assign icmp_ln151_fu_2699_p2 = ((ap_phi_mux_w_index48_phi_fu_1018_p6 == 10'd999) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_2685_p2 = (($signed(in_index_fu_2679_p2) > $signed(32'd99)) ? 1'b1 : 1'b0);

assign in_index_fu_2679_p2 = (ap_phi_mux_in_index_0_i47_phi_fu_1032_p6 + 32'd1);

assign outidx_address0 = zext_ln155_fu_2057_p1;

assign res_0_V = {{ap_phi_mux_p_Val2_48_phi_fu_2025_p20[15:7]}};

assign res_1_V = {{ap_phi_mux_p_Val2_49_phi_fu_1989_p20[15:7]}};

assign res_2_V = {{ap_phi_mux_p_Val2_50_phi_fu_1953_p20[15:7]}};

assign res_3_V = {{ap_phi_mux_p_Val2_51_phi_fu_1917_p20[15:7]}};

assign res_4_V = {{ap_phi_mux_p_Val2_52_phi_fu_1881_p20[15:7]}};

assign res_5_V = {{ap_phi_mux_p_Val2_53_phi_fu_1845_p20[15:7]}};

assign res_6_V = {{ap_phi_mux_p_Val2_54_phi_fu_1809_p20[15:7]}};

assign res_7_V = {{ap_phi_mux_p_Val2_55_phi_fu_1773_p20[15:7]}};

assign res_8_V = {{ap_phi_mux_p_Val2_56_phi_fu_1737_p20[15:7]}};

assign res_9_V = {{ap_phi_mux_p_Val2_57_phi_fu_1701_p20[15:7]}};

assign select_ln168_fu_2691_p3 = ((icmp_ln168_fu_2685_p2[0:0] === 1'b1) ? 32'd0 : in_index_fu_2679_p2);

assign tmp_4_fu_2467_p1 = data_0_V;

assign tmp_4_fu_2467_p10 = data_9_V;

assign tmp_4_fu_2467_p100 = data_99_V;

assign tmp_4_fu_2467_p101 = ap_phi_mux_in_index_0_i47_phi_fu_1032_p6[6:0];

assign tmp_4_fu_2467_p11 = data_10_V;

assign tmp_4_fu_2467_p12 = data_11_V;

assign tmp_4_fu_2467_p13 = data_12_V;

assign tmp_4_fu_2467_p14 = data_13_V;

assign tmp_4_fu_2467_p15 = data_14_V;

assign tmp_4_fu_2467_p16 = data_15_V;

assign tmp_4_fu_2467_p17 = data_16_V;

assign tmp_4_fu_2467_p18 = data_17_V;

assign tmp_4_fu_2467_p19 = data_18_V;

assign tmp_4_fu_2467_p2 = data_1_V;

assign tmp_4_fu_2467_p20 = data_19_V;

assign tmp_4_fu_2467_p21 = data_20_V;

assign tmp_4_fu_2467_p22 = data_21_V;

assign tmp_4_fu_2467_p23 = data_22_V;

assign tmp_4_fu_2467_p24 = data_23_V;

assign tmp_4_fu_2467_p25 = data_24_V;

assign tmp_4_fu_2467_p26 = data_25_V;

assign tmp_4_fu_2467_p27 = data_26_V;

assign tmp_4_fu_2467_p28 = data_27_V;

assign tmp_4_fu_2467_p29 = data_28_V;

assign tmp_4_fu_2467_p3 = data_2_V;

assign tmp_4_fu_2467_p30 = data_29_V;

assign tmp_4_fu_2467_p31 = data_30_V;

assign tmp_4_fu_2467_p32 = data_31_V;

assign tmp_4_fu_2467_p33 = data_32_V;

assign tmp_4_fu_2467_p34 = data_33_V;

assign tmp_4_fu_2467_p35 = data_34_V;

assign tmp_4_fu_2467_p36 = data_35_V;

assign tmp_4_fu_2467_p37 = data_36_V;

assign tmp_4_fu_2467_p38 = data_37_V;

assign tmp_4_fu_2467_p39 = data_38_V;

assign tmp_4_fu_2467_p4 = data_3_V;

assign tmp_4_fu_2467_p40 = data_39_V;

assign tmp_4_fu_2467_p41 = data_40_V;

assign tmp_4_fu_2467_p42 = data_41_V;

assign tmp_4_fu_2467_p43 = data_42_V;

assign tmp_4_fu_2467_p44 = data_43_V;

assign tmp_4_fu_2467_p45 = data_44_V;

assign tmp_4_fu_2467_p46 = data_45_V;

assign tmp_4_fu_2467_p47 = data_46_V;

assign tmp_4_fu_2467_p48 = data_47_V;

assign tmp_4_fu_2467_p49 = data_48_V;

assign tmp_4_fu_2467_p5 = data_4_V;

assign tmp_4_fu_2467_p50 = data_49_V;

assign tmp_4_fu_2467_p51 = data_50_V;

assign tmp_4_fu_2467_p52 = data_51_V;

assign tmp_4_fu_2467_p53 = data_52_V;

assign tmp_4_fu_2467_p54 = data_53_V;

assign tmp_4_fu_2467_p55 = data_54_V;

assign tmp_4_fu_2467_p56 = data_55_V;

assign tmp_4_fu_2467_p57 = data_56_V;

assign tmp_4_fu_2467_p58 = data_57_V;

assign tmp_4_fu_2467_p59 = data_58_V;

assign tmp_4_fu_2467_p6 = data_5_V;

assign tmp_4_fu_2467_p60 = data_59_V;

assign tmp_4_fu_2467_p61 = data_60_V;

assign tmp_4_fu_2467_p62 = data_61_V;

assign tmp_4_fu_2467_p63 = data_62_V;

assign tmp_4_fu_2467_p64 = data_63_V;

assign tmp_4_fu_2467_p65 = data_64_V;

assign tmp_4_fu_2467_p66 = data_65_V;

assign tmp_4_fu_2467_p67 = data_66_V;

assign tmp_4_fu_2467_p68 = data_67_V;

assign tmp_4_fu_2467_p69 = data_68_V;

assign tmp_4_fu_2467_p7 = data_6_V;

assign tmp_4_fu_2467_p70 = data_69_V;

assign tmp_4_fu_2467_p71 = data_70_V;

assign tmp_4_fu_2467_p72 = data_71_V;

assign tmp_4_fu_2467_p73 = data_72_V;

assign tmp_4_fu_2467_p74 = data_73_V;

assign tmp_4_fu_2467_p75 = data_74_V;

assign tmp_4_fu_2467_p76 = data_75_V;

assign tmp_4_fu_2467_p77 = data_76_V;

assign tmp_4_fu_2467_p78 = data_77_V;

assign tmp_4_fu_2467_p79 = data_78_V;

assign tmp_4_fu_2467_p8 = data_7_V;

assign tmp_4_fu_2467_p80 = data_79_V;

assign tmp_4_fu_2467_p81 = data_80_V;

assign tmp_4_fu_2467_p82 = data_81_V;

assign tmp_4_fu_2467_p83 = data_82_V;

assign tmp_4_fu_2467_p84 = data_83_V;

assign tmp_4_fu_2467_p85 = data_84_V;

assign tmp_4_fu_2467_p86 = data_85_V;

assign tmp_4_fu_2467_p87 = data_86_V;

assign tmp_4_fu_2467_p88 = data_87_V;

assign tmp_4_fu_2467_p89 = data_88_V;

assign tmp_4_fu_2467_p9 = data_8_V;

assign tmp_4_fu_2467_p90 = data_89_V;

assign tmp_4_fu_2467_p91 = data_90_V;

assign tmp_4_fu_2467_p92 = data_91_V;

assign tmp_4_fu_2467_p93 = data_92_V;

assign tmp_4_fu_2467_p94 = data_93_V;

assign tmp_4_fu_2467_p95 = data_94_V;

assign tmp_4_fu_2467_p96 = data_95_V;

assign tmp_4_fu_2467_p97 = data_96_V;

assign tmp_4_fu_2467_p98 = data_97_V;

assign tmp_4_fu_2467_p99 = data_98_V;

assign w8_V_address0 = zext_ln155_fu_2057_p1;

assign w_index_fu_2673_p2 = (10'd1 + ap_phi_mux_w_index48_phi_fu_1018_p6);

assign zext_ln155_fu_2057_p1 = ap_phi_mux_w_index48_phi_fu_1018_p6;

endmodule //dense_resource_ap_fixed_ap_fixed_9_6_5_3_0_config8_s
